//! Native port of client/src/sim/draftWeights.ts + the offer-rolling core
//! loop in client/src/sim/round.ts's enterDrafting (lines ~443-464).
//!
//! Scope: this ports the weighted-offer-generation ALGORITHM with proven
//! RNG-cursor parity against the real TS implementation (golden vectors
//! below, generated by running the actual TS code — see the comment on
//! each test). It does NOT yet wire into world.zig's round-phase machine:
//! there's no WorldState field for draftingOffers/draftingPicked/
//! draftingExpiresAtTick, and no phase transition from round-over into a
//! `drafting` phase (round.zig's roundStepPhase stays a pure phase-timer
//! function with no score/drafting awareness by design — see its own
//! doc comment). That's a substantial follow-on: new wire-format fields,
//! phase-transition wiring, and a host-callable pick-commit export. The
//! server-side applyDraftingOverlay TS path already makes drafting fully
//! functional in production today, so this gap is architectural
//! self-containment for step_world, not a live correctness bug.
//!
//! candidate-pool filtering (unique-already-owned, maxStacks cap) is the
//! caller's job — see `poolIndices` below for the filtering helper, kept
//! separate from the RNG-consuming roll so callers can build the pool once
//! per player from cards_gen's static unique/max_stacks metadata.

const std = @import("std");
const rng = @import("rng.zig");
pub const gen = @import("data/cards_gen.zig");

pub const DRAFT_OFFER_COUNT: u32 = 3;
pub const MAX_OFFER_COUNT: u32 = DRAFT_OFFER_COUNT;

pub const DraftRole = enum { standard, catch_up, winner };

/// Mirrors draftWeights.ts's classifyDraftRole exactly.
pub fn classifyDraftRole(is_self: bool, has_winner: bool) DraftRole {
    if (!has_winner) return .standard;
    return if (is_self) .winner else .catch_up;
}

/// Mirrors draftWeights.ts's weightForCard exactly. `entry` is a
/// cards_gen.CardEntry; catch_up_eligible/rarity are precomputed at codegen
/// time (see gen_card_data.ts) from the TS card's buckets/rarity fields.
pub fn weightForCard(entry: gen.CardEntry, role: DraftRole) f64 {
    if (role != .catch_up) return 1;
    var w: f64 = 1;
    if (entry.catch_up_eligible) w += 2;
    if (entry.rarity == 1) w += 1; // uncommon
    if (entry.rarity == 2 or entry.rarity == 3) w += 2; // rare | legendary
    return w;
}

/// Mirrors draftWeights.ts's pickWeighted exactly, operating over a slice
/// of indices into gen.cards (rather than the cards themselves) so callers
/// can pass a filtered/shrinking candidate list without copying CardEntry
/// values. Returns the new rng cursor and the picked index-into-`indices`
/// (NOT the card index itself — mirrors the TS fn returning the item).
pub const PickResult = struct { cursor: u32, picked_pos: usize };

pub fn pickWeighted(cursor: u32, indices: []const u32, role: DraftRole) PickResult {
    std.debug.assert(indices.len > 0);
    var total: f64 = 0;
    var weights_buf: [gen.cards.len]f64 = undefined;
    const weights = weights_buf[0..indices.len];
    for (indices, 0..) |card_idx, i| {
        const w = @max(0.0, weightForCard(gen.cards[card_idx], role));
        weights[i] = w;
        total += w;
    }
    const new_state = rng.nextU32(cursor);
    if (total <= 0) {
        return .{ .cursor = new_state, .picked_pos = 0 };
    }
    const f: f64 = @as(f64, @floatFromInt(new_state)) / 4294967296.0;
    var r = f * total;
    var i: usize = 0;
    while (i < indices.len) : (i += 1) {
        r -= weights[i];
        if (r <= 0) return .{ .cursor = new_state, .picked_pos = i };
    }
    return .{ .cursor = new_state, .picked_pos = indices.len - 1 };
}

/// Mirrors round.ts's candidatePool filter: excludes `unique` cards already
/// in `owned`, and cards already held at `maxStacks` copies (via `copyCountOf`,
/// a caller-supplied closure over the player's hand — kept generic so this
/// doesn't need a WorldState/hand representation to compile against yet).
/// Writes matching indices into `out`, returns count written.
pub fn poolIndices(
    owned: []const bool, // owned[card_idx] = true if in hand at all
    copies: []const u32, // copies[card_idx] = stack count in hand
    out: []u32,
) usize {
    var n: usize = 0;
    for (gen.cards, 0..) |entry, idx| {
        if (entry.unique and owned[idx]) continue;
        if (entry.max_stacks) |cap| {
            if (copies[idx] >= cap) continue;
        }
        if (n < out.len) {
            out[n] = @intCast(idx);
            n += 1;
        }
    }
    return n;
}

pub const RollResult = struct {
    cursor: u32,
    offers: [MAX_OFFER_COUNT]u32 = @splat(0),
    count: u32 = 0,
};

/// Mirrors round.ts's enterDrafting inner while-loop exactly (lines
/// ~443-464): repeatedly filters the candidate pool down to not-yet-seen
/// entries (preserving original pool order — matches TS's `.filter`, NOT a
/// swap-remove), weighted-picks from what remains, and stops once `target`
/// unique offers are collected or the `target*8` bounded-retry cap is hit.
pub fn rollOffers(cursor: u32, pool: []const u32, role: DraftRole) RollResult {
    var result = RollResult{ .cursor = cursor };
    if (pool.len == 0) return result;
    const target: u32 = @min(DRAFT_OFFER_COUNT, @as(u32, @intCast(pool.len)));
    var seen: [gen.cards.len]bool = @splat(false);
    var remaining_buf: [gen.cards.len]u32 = undefined;
    var attempts: u32 = 0;
    var c = cursor;
    while (result.count < target and attempts < target * 8) {
        var remaining_len: usize = 0;
        for (pool) |card_idx| {
            if (!seen[card_idx]) {
                remaining_buf[remaining_len] = card_idx;
                remaining_len += 1;
            }
        }
        if (remaining_len == 0) break;
        const remaining = remaining_buf[0..remaining_len];
        const pr = pickWeighted(c, remaining, role);
        c = pr.cursor;
        const picked_idx = remaining[pr.picked_pos];
        if (!seen[picked_idx]) {
            seen[picked_idx] = true;
            result.offers[result.count] = picked_idx;
            result.count += 1;
        }
        attempts += 1;
    }
    result.cursor = c;
    return result;
}
