// Syzygist Devotion resource (class-overhaul-workboard.md chunk 3.2:
// "Devotion resource... generated by buff/heal uptime ON OTHERS"). Proves
// World.ts's per-tick Devotion-accrual pass directly against
// stepWithRuntime — continuous per-tick income scaled by the count of
// DISTINCT other allies currently carrying a live regen/haste/Ward window
// sourced from this player, capped at SYZ_DEVOTION_MAX_COUNTED_SOURCES
// sources and SYZ_DEVOTION_MAX total. See constants.ts's SYZ_DEVOTION_*
// header note for the full counting-rule design rationale.

import { describe, expect, test } from "bun:test";
import { createRuntime, stepWithRuntime, applyRegenToAlly, applyHasteToAlly, applyWardToAlly } from "../World.js";
import {
  SYZ_DEVOTION_MAX,
  SYZ_DEVOTION_PER_BUFFED_ALLY_PER_SEC,
  SYZ_DEVOTION_MAX_COUNTED_SOURCES,
  SYZ_SNOWBALL_BRAKE_FLOOR,
} from "../constants.js";
import {
  InputSeq,
  PlayerId,
  Tick,
  type InputFrame,
  type MapDefinition,
  type PlayerEntity,
  type WorldState,
} from "../types.js";

const DT_MS = 1000 / 60;

const flatMap: MapDefinition = {
  id: "test",
  name: "test",
  size: { x: 1280, y: 720 },
  spawns: [
    { x: 200, y: 400 },
    { x: 600, y: 400 },
    { x: 900, y: 400 },
    { x: 1000, y: 400 },
    { x: 1100, y: 400 },
  ],
  // Platform `position` is CENTER-origin (collision.ts's platformToAABB) —
  // a 1280-wide floor centered at x=0 only spans [-640, 640]. This fixture
  // needs multi-player tests spread further right (x up to ~1100), so the
  // floor is centered at the map's own midpoint with the full map width,
  // covering every test position in this file.
  platforms: [
    { id: "floor", kind: "floor", position: { x: 640, y: 500 }, size: { x: 1280, y: 60 } },
  ],
};

function mkPlayer(id: PlayerId, x: number, y: number, over: Partial<PlayerEntity> = {}): PlayerEntity {
  return {
    id, characterId: "shielded", x, y, vx: 0, vy: 0,
    aimX: x + 100, aimY: y, health: 100, shieldActive: false, crouching: false,
    alive: true, weaponId: "starter-pistol", cards: [], fireCooldownMs: 0,
    ammo: 0, abilityCharge: 0, lastProcessedInputSeq: InputSeq(0), ...over,
  };
}

function mkState(players: PlayerEntity[]): WorldState {
  const playerMap: Record<PlayerId, PlayerEntity> = {};
  for (const p of players) playerMap[p.id] = p;
  return {
    tick: Tick(0), rngState: 1234567 >>> 0, players: playerMap, projectiles: {},
    destructibles: {}, firePatches: {}, pickups: {}, satellites: {},
    round: {
      phase: "fighting", countdownRemainingMs: 90_000,
      scores: Object.fromEntries(players.map((p) => [p.id, 0])),
      roundIndex: 0, winnerPlayerId: null,
    },
  };
}

function inputsWith(
  players: PlayerEntity[],
  overrides: Partial<Record<string, InputFrame>>,
): Record<PlayerId, InputFrame | null> {
  const out: Record<PlayerId, InputFrame | null> = {};
  for (const p of players) out[p.id] = overrides[p.id as string] ?? null;
  return out;
}

const A = PlayerId("a"); // Syzygist caster
const B = PlayerId("b"); // ally
const C = PlayerId("c"); // ally #2
const D = PlayerId("d"); // enemy / non-ally
const E = PlayerId("e"); // ally #3 (for the cap test)
const F = PlayerId("f"); // ally #4
const G = PlayerId("g"); // ally #5 (over the cap)

describe("Devotion accrual — generates while an ally carries the caster's buff", () => {
  test("devotion climbs continuously while a regen window from this caster is live on an ally", () => {
    const caster = mkPlayer(A, 400, 400, { teamId: "t1" });
    const ally = mkPlayer(B, 500, 400, { teamId: "t1" });
    let state = mkState([caster, ally]);
    const runtime = createRuntime(flatMap);
    applyRegenToAlly(caster, ally, state.players, state.tick, 6, 600);

    for (let i = 0; i < 60; i++) {
      const res = stepWithRuntime(state, runtime, inputsWith([caster, ally], {}), DT_MS);
      state = res.state;
    }
    // 60 ticks at 60Hz = 1 real second: 1 source * rate * 1s.
    expect(state.players[A]!.devotion).toBeCloseTo(SYZ_DEVOTION_PER_BUFFED_ALLY_PER_SEC, 1);
    // The ally never earns devotion themselves — only the SOURCE caster does.
    expect(state.players[B]!.devotion ?? 0).toBe(0);
  });

  test("does NOT generate when no ally carries any buff", () => {
    const caster = mkPlayer(A, 400, 400, { teamId: "t1" });
    const ally = mkPlayer(B, 500, 400, { teamId: "t1" }); // present, but un-buffed
    let state = mkState([caster, ally]);
    const runtime = createRuntime(flatMap);
    for (let i = 0; i < 120; i++) {
      const res = stepWithRuntime(state, runtime, inputsWith([caster, ally], {}), DT_MS);
      state = res.state;
    }
    expect(state.players[A]!.devotion ?? 0).toBe(0);
  });

  test("does NOT generate for a solo/FFA caster (no teamId) even standing next to another player", () => {
    const caster = mkPlayer(A, 400, 400); // no teamId
    const other = mkPlayer(B, 420, 400);
    let state = mkState([caster, other]);
    const runtime = createRuntime(flatMap);
    for (let i = 0; i < 120; i++) {
      const res = stepWithRuntime(state, runtime, inputsWith([caster, other], {}), DT_MS);
      state = res.state;
    }
    expect(state.players[A]!.devotion ?? 0).toBe(0);
  });

  test("does NOT generate from a buff on a non-ally (an enemy can never carry this caster's buff at all — isAlly gates the write itself)", () => {
    const caster = mkPlayer(A, 400, 400, { teamId: "t1" });
    const enemy = mkPlayer(D, 500, 400, { teamId: "t2" });
    let state = mkState([caster, enemy]);
    // applyRegenToAlly itself refuses a non-ally target — this proves the
    // devotion pass has nothing to count even if somehow called.
    const applied = applyRegenToAlly(caster, enemy, state.players, state.tick, 6, 600);
    expect(applied).toBe(false);
    const runtime = createRuntime(flatMap);
    for (let i = 0; i < 60; i++) {
      const res = stepWithRuntime(state, runtime, inputsWith([caster, enemy], {}), DT_MS);
      state = res.state;
    }
    expect(state.players[A]!.devotion ?? 0).toBe(0);
  });

  test("stops generating the instant the buff window expires", () => {
    const caster = mkPlayer(A, 400, 400, { teamId: "t1" });
    const ally = mkPlayer(B, 500, 400, { teamId: "t1" });
    let state = mkState([caster, ally]);
    const runtime = createRuntime(flatMap);
    // A short window (10 ticks) — closes almost immediately.
    applyRegenToAlly(caster, ally, state.players, state.tick, 6, 10);
    for (let i = 0; i < 12; i++) {
      const res = stepWithRuntime(state, runtime, inputsWith([caster, ally], {}), DT_MS);
      state = res.state;
    }
    const devotionAtExpiry = state.players[A]!.devotion ?? 0;
    expect(devotionAtExpiry).toBeGreaterThan(0); // it DID generate while live
    // Advance further — devotion must hold steady, not keep climbing.
    for (let i = 0; i < 60; i++) {
      const res = stepWithRuntime(state, runtime, inputsWith([caster, ally], {}), DT_MS);
      state = res.state;
    }
    expect(state.players[A]!.devotion).toBeCloseTo(devotionAtExpiry, 5);
  });
});

describe("Devotion accrual — dedup and attribution", () => {
  test("an ally carrying BOTH regen and haste from the SAME caster still counts as ONE source, not two", () => {
    const caster = mkPlayer(A, 400, 400, { teamId: "t1" });
    const ally = mkPlayer(B, 500, 400, { teamId: "t1" });
    let stateDouble = mkState([caster, ally]);
    const runtimeDouble = createRuntime(flatMap);
    applyRegenToAlly(caster, ally, stateDouble.players, stateDouble.tick, 6, 600);
    applyHasteToAlly(caster, ally, stateDouble.players, stateDouble.tick, 1.25, 600);
    for (let i = 0; i < 60; i++) {
      const res = stepWithRuntime(stateDouble, runtimeDouble, inputsWith([caster, ally], {}), DT_MS);
      stateDouble = res.state;
    }

    const casterSingle = mkPlayer(A, 400, 400, { teamId: "t1" });
    const allySingle = mkPlayer(B, 500, 400, { teamId: "t1" });
    let stateSingle = mkState([casterSingle, allySingle]);
    const runtimeSingle = createRuntime(flatMap);
    applyRegenToAlly(casterSingle, allySingle, stateSingle.players, stateSingle.tick, 6, 600);
    for (let i = 0; i < 60; i++) {
      const res = stepWithRuntime(stateSingle, runtimeSingle, inputsWith([casterSingle, allySingle], {}), DT_MS);
      stateSingle = res.state;
    }

    expect(stateDouble.players[A]!.devotion).toBeCloseTo(stateSingle.players[A]!.devotion!, 1);
  });

  test("two different allies each carrying a buff from the SAME caster count as TWO sources (double rate)", () => {
    const caster = mkPlayer(A, 400, 400, { teamId: "t1" });
    const allyB = mkPlayer(B, 500, 400, { teamId: "t1" });
    const allyC = mkPlayer(C, 600, 400, { teamId: "t1" });
    let state = mkState([caster, allyB, allyC]);
    const runtime = createRuntime(flatMap);
    applyRegenToAlly(caster, allyB, state.players, state.tick, 6, 600);
    applyRegenToAlly(caster, allyC, state.players, state.tick, 6, 600);
    for (let i = 0; i < 60; i++) {
      const res = stepWithRuntime(state, runtime, inputsWith([caster, allyB, allyC], {}), DT_MS);
      state = res.state;
    }
    expect(state.players[A]!.devotion).toBeCloseTo(2 * SYZ_DEVOTION_PER_BUFFED_ALLY_PER_SEC, 1);
  });

  test("devotion accrues to the CORRECT caster when two different Syzygists buff different allies", () => {
    const casterA = mkPlayer(A, 400, 400, { teamId: "t1" });
    const allyB = mkPlayer(B, 500, 400, { teamId: "t1" });
    const casterC = mkPlayer(C, 800, 400, { teamId: "t2" });
    const allyD = mkPlayer(D, 900, 400, { teamId: "t2" });
    let state = mkState([casterA, allyB, casterC, allyD]);
    const runtime = createRuntime(flatMap);
    applyRegenToAlly(casterA, allyB, state.players, state.tick, 6, 600);
    // caster C buffs ally D on a DIFFERENT team — must never bleed into A's total.
    applyHasteToAlly(casterC, allyD, state.players, state.tick, 1.25, 600);
    for (let i = 0; i < 60; i++) {
      const res = stepWithRuntime(state, runtime, inputsWith([casterA, allyB, casterC, allyD], {}), DT_MS);
      state = res.state;
    }
    expect(state.players[A]!.devotion).toBeCloseTo(SYZ_DEVOTION_PER_BUFFED_ALLY_PER_SEC, 1);
    expect(state.players[C]!.devotion).toBeCloseTo(SYZ_DEVOTION_PER_BUFFED_ALLY_PER_SEC, 1);
    // Neither the buffed allies nor the "wrong" caster earn anything.
    expect(state.players[B]!.devotion ?? 0).toBe(0);
    expect(state.players[D]!.devotion ?? 0).toBe(0);
  });
});

describe("Devotion accrual — Ward also counts as a carried effect", () => {
  test("an ally carrying this caster's live Ward pool grants devotion too", () => {
    const caster = mkPlayer(A, 400, 400, { teamId: "t1" });
    const ally = mkPlayer(B, 500, 400, { teamId: "t1" });
    let state = mkState([caster, ally]);
    const runtime = createRuntime(flatMap);
    applyWardToAlly(caster, ally, state.players, state.tick, 30, 600);
    for (let i = 0; i < 60; i++) {
      const res = stepWithRuntime(state, runtime, inputsWith([caster, ally], {}), DT_MS);
      state = res.state;
    }
    expect(state.players[A]!.devotion).toBeCloseTo(SYZ_DEVOTION_PER_BUFFED_ALLY_PER_SEC, 1);
  });
});

describe("Devotion accrual — caps", () => {
  test("caps the per-tick source count at SYZ_DEVOTION_MAX_COUNTED_SOURCES", () => {
    const caster = mkPlayer(A, 400, 400, { teamId: "t1" });
    const allies = [B, C, E, F, G].map((id, i) => mkPlayer(id, 500 + i * 40, 400, { teamId: "t1" }));
    let state = mkState([caster, ...allies]);
    const runtime = createRuntime(flatMap);
    for (const ally of allies) {
      applyRegenToAlly(caster, ally, state.players, state.tick, 6, 600);
    }
    // 5 allies buffed — one more than SYZ_DEVOTION_MAX_COUNTED_SOURCES (4).
    for (let i = 0; i < 60; i++) {
      const res = stepWithRuntime(state, runtime, inputsWith([caster, ...allies], {}), DT_MS);
      state = res.state;
    }
    expect(SYZ_DEVOTION_MAX_COUNTED_SOURCES).toBe(4);
    expect(state.players[A]!.devotion).toBeCloseTo(
      SYZ_DEVOTION_MAX_COUNTED_SOURCES * SYZ_DEVOTION_PER_BUFFED_ALLY_PER_SEC,
      1,
    );
  });

  test("caps total devotion at SYZ_DEVOTION_MAX — never overflows", () => {
    const caster = mkPlayer(A, 400, 400, { teamId: "t1", devotion: SYZ_DEVOTION_MAX - 0.5 });
    const ally = mkPlayer(B, 500, 400, { teamId: "t1" });
    let state = mkState([caster, ally]);
    const runtime = createRuntime(flatMap);
    applyRegenToAlly(caster, ally, state.players, state.tick, 6, 600);
    for (let i = 0; i < 30; i++) {
      const res = stepWithRuntime(state, runtime, inputsWith([caster, ally], {}), DT_MS);
      state = res.state;
    }
    expect(state.players[A]!.devotion).toBe(SYZ_DEVOTION_MAX);
  });
});

// D3 brake (docs/axiom-deviations-audit.md's Syzygist entry — "one shared
// stopping mechanism... brakes [Devotion accrual and Flock Pulse] at once",
// "prefer difference-fed brakes: tie the friction to how far AHEAD the
// loop's owner is... invisible when you're even, firm when you're
// snowballing"). Proves the SAME buff uptime (identical source count, same
// rate constant) earns Devotion at a genuinely different — not just
// numerically smaller-but-still-linear — pace once the caster is pulling
// ahead in-round, and earns at the OLD, unbraked, full rate whenever the
// caster is even or behind. `state.round.roundKills` is set directly on the
// fixture (no new plumbing — the same field `decideRoundWinner`, round.ts,
// already reads) since these tests don't exercise real combat kills.
describe("Devotion accrual — D3 snowball brake (in-round kill lead)", () => {
  test("identical buff setup: an even/behind caster earns at the OLD unbraked rate; a caster 3 kills ahead earns at the braked floor", () => {
    const caster = mkPlayer(A, 400, 400, { teamId: "t1" });
    const ally = mkPlayer(B, 500, 400, { teamId: "t1" });
    const rival = mkPlayer(D, 700, 400); // no teamId — "the field", not this caster's ally

    // Baseline: no round-kill picture at all (mkState's default) — this IS
    // today's pre-brake behavior, unchanged. One source, full rate.
    let baseline = mkState([caster, ally, rival]);
    const baselineRuntime = createRuntime(flatMap);
    applyRegenToAlly(caster, ally, baseline.players, baseline.tick, 6, 600);
    for (let i = 0; i < 60; i++) {
      const res = stepWithRuntime(baseline, baselineRuntime, inputsWith([caster, ally, rival], {}), DT_MS);
      baseline = res.state;
    }
    const unbrakedGain = baseline.players[A]!.devotion ?? 0;
    // Sanity: matches the pre-existing "generates while a regen window is
    // live" test above exactly — proves the baseline IS the old math.
    expect(unbrakedGain).toBeCloseTo(SYZ_DEVOTION_PER_BUFFED_ALLY_PER_SEC, 1);

    // Snowballing: caster A is 3 kills ahead of the round's OTHER alive
    // players (ally B and rival D both sit at 0) — identical buff setup,
    // only the round-kill picture differs.
    let ahead = mkState([caster, ally, rival]);
    ahead = {
      ...ahead,
      round: { ...ahead.round, roundKills: { [A]: 3 } as Record<PlayerId, number> },
    };
    const aheadRuntime = createRuntime(flatMap);
    applyRegenToAlly(caster, ally, ahead.players, ahead.tick, 6, 600);
    for (let i = 0; i < 60; i++) {
      const res = stepWithRuntime(ahead, aheadRuntime, inputsWith([caster, ally, rival], {}), DT_MS);
      ahead = res.state;
    }
    const brakedGain = ahead.players[A]!.devotion ?? 0;

    // A 3-kill lead already reaches SYZ_SNOWBALL_BRAKE_FLOOR (0.25 lost per
    // kill of lead, floored at 0.25) — the SAME source count now earns at a
    // quarter of the old rate, a real reduction, not cosmetic rounding.
    expect(brakedGain).toBeCloseTo(unbrakedGain * SYZ_SNOWBALL_BRAKE_FLOOR, 1);
    expect(brakedGain).toBeLessThan(unbrakedGain);
  });

  test("even (tied roundKills) and BEHIND casters both earn at the full, unbraked rate — the brake is invisible unless actually ahead", () => {
    const caster = mkPlayer(A, 400, 400, { teamId: "t1" });
    const ally = mkPlayer(B, 500, 400, { teamId: "t1" });
    const rival = mkPlayer(D, 700, 400);

    let tied = mkState([caster, ally, rival]);
    // "Tied" means the AVERAGE of every other alive player (ally B included,
    // per syzygistLeadBrakeMultiplier's own doc comment) equals the
    // caster's own count — so both B and D need the same figure as A.
    tied = { ...tied, round: { ...tied.round, roundKills: { [A]: 2, [B]: 2, [D]: 2 } as Record<PlayerId, number> } };
    const tiedRuntime = createRuntime(flatMap);
    applyRegenToAlly(caster, ally, tied.players, tied.tick, 6, 600);
    for (let i = 0; i < 60; i++) {
      const res = stepWithRuntime(tied, tiedRuntime, inputsWith([caster, ally, rival], {}), DT_MS);
      tied = res.state;
    }
    expect(tied.players[A]!.devotion).toBeCloseTo(SYZ_DEVOTION_PER_BUFFED_ALLY_PER_SEC, 1);

    let behind = mkState([caster, ally, rival]);
    behind = { ...behind, round: { ...behind.round, roundKills: { [A]: 0, [D]: 5 } as Record<PlayerId, number> } };
    const behindRuntime = createRuntime(flatMap);
    applyRegenToAlly(caster, ally, behind.players, behind.tick, 6, 600);
    for (let i = 0; i < 60; i++) {
      const res = stepWithRuntime(behind, behindRuntime, inputsWith([caster, ally, rival], {}), DT_MS);
      behind = res.state;
    }
    expect(behind.players[A]!.devotion).toBeCloseTo(SYZ_DEVOTION_PER_BUFFED_ALLY_PER_SEC, 1);
  });

  test("the brake never fully zeroes Devotion income, even at a large lead (floor, not silence)", () => {
    const caster = mkPlayer(A, 400, 400, { teamId: "t1" });
    const ally = mkPlayer(B, 500, 400, { teamId: "t1" });
    let state = mkState([caster, ally]);
    // A wildly lopsided lead (10 kills vs the ally's 0) — well past the
    // point the linear taper would go negative without the floor clamp.
    state = { ...state, round: { ...state.round, roundKills: { [A]: 10 } as Record<PlayerId, number> } };
    const runtime = createRuntime(flatMap);
    applyRegenToAlly(caster, ally, state.players, state.tick, 6, 600);
    for (let i = 0; i < 60; i++) {
      const res = stepWithRuntime(state, runtime, inputsWith([caster, ally], {}), DT_MS);
      state = res.state;
    }
    const gain = state.players[A]!.devotion ?? 0;
    expect(gain).toBeGreaterThan(0);
    expect(gain).toBeCloseTo(SYZ_DEVOTION_PER_BUFFED_ALLY_PER_SEC * SYZ_SNOWBALL_BRAKE_FLOOR, 1);
  });
});
