// Codegen: TS card/weapon data → sim/src/data/cards_gen.zig.
//
// cards.ts stays the SINGLE source of truth (the UI reads it for names/icons);
// this emits the sim-relevant modifier table into Zig so the Zig orchestrator
// resolves builds in-sim (no host-side createWeaponBuild). Re-run on card
// changes: `bun run sim/tools/gen_card_data.ts`. Field order + semantics mirror
// weaponBuild.ts createWeaponBuild/applyCard/mergeProjectileModifier.

import { crystalRoundsCards } from "../../client/src/sim/data/cards.ts";
import { starterWeapon } from "../../client/src/sim/data/weapons.ts";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SHAPE = ["circle", "triangle", "square", "hexagon", "orb", "x", "bar"];
const ELEMENT = ["crystal", "neutral", "fire", "ice", "lightning", "void", "radiant", "electric", "toxic", "sticky", "explosive"];
const PATHING = ["straight", "gravity", "bounce", "boomerang", "homing", "anti-homing", "float", "accelerate"];
const IMPACT = ["none", "explosive", "sticky", "pierce-chain", "slow-field"];
const idx = (arr: string[], v: string | undefined): number | null =>
  v === undefined ? null : Math.max(0, arr.indexOf(v));

const f = (n: number | undefined, dflt: number): string =>
  (n ?? dflt).toString().includes(".") || !Number.isFinite(n ?? dflt)
    ? `${n ?? dflt}`
    : `${n ?? dflt}.0`;
const optF = (n: number | undefined): string => (n === undefined ? "null" : f(n, 0));
const optI = (n: number | null): string => (n === null ? "null" : `${n}`);

// The fields that reach ResolvedFireConfig (packResolvedFireConfig) — others
// (reload/recoil/magazine/ammo) never cross the sim boundary and are skipped.
function cardLiteral(id: string, mod: NonNullable<(typeof crystalRoundsCards)[number]["modifier"]>): string {
  const p = mod.projectile;
  const parts: string[] = [];
  const add = (name: string, val: string, isDefault: string) => {
    if (val !== isDefault) parts.push(`.${name} = ${val}`);
  };
  add("damage_mul", f(mod.damageMultiplier, 1), "1.0");
  add("fire_rate_mul", f(mod.fireRateMultiplier, 1), "1.0");
  add("projectile_speed_mul", f(mod.projectileSpeedMultiplier, 1), "1.0");
  add("spread_radians_add", f(mod.spreadRadiansAdd, 0), "0.0");
  add("spread_radians_set", optF(mod.spreadRadians), "null");
  add("max_health_add", f(mod.maxHealthAdd, 0), "0.0");
  add("move_speed_mul", f(mod.moveSpeedMultiplier, 1), "1.0");
  add("parry_cover_mul", f(mod.parryCoverMultiplier, 1), "1.0");
  add("parry_cooldown_mul", f(mod.parryCooldownMultiplier, 1), "1.0");
  add("gravity_mul", f(mod.gravityMultiplier, 1), "1.0");
  add("shield_charge_mul", f(mod.shieldChargeMultiplier, 1), "1.0");
  add("shield_recharge_mul", f(mod.shieldRechargeMultiplier, 1), "1.0");
  add("jump_mul", f(mod.jumpMultiplier, 1), "1.0");
  add("wall_jump_mul", f(mod.wallJumpMultiplier, 1), "1.0");
  add("wall_slide_mul", f(mod.wallSlideMultiplier, 1), "1.0");
  add("air_jumps_add", f(mod.airJumpsAdd, 0), "0.0");
  add("dash_charges_add", f(mod.dashChargesAdd, 0), "0.0");
  add("mirror_shield", mod.mirrorShield ? "true" : "false", "false");
  add("directional_shield", mod.directionalShield ? "true" : "false", "false");
  add("proj_count_add", f(mod.projectileCountAdd, 0), "0.0");
  add("proj_bounce_add", f(mod.projectileBounceAdd, 0), "0.0");
  add("proj_split_add", f(mod.projectileSplitAdd, 0), "0.0");
  add("proj_homing_add", f(mod.projectileHomingStrengthAdd, 0), "0.0");
  if (p) {
    add("proj_speed_mul", f(p.speedMultiplier, 1), "1.0");
    add("proj_size_mul", f(p.sizeMultiplier, 1), "1.0");
    add("proj_lifetime_mul", f(p.lifetimeMultiplier, 1), "1.0");
    add("proj_shape", optI(idx(SHAPE, p.shape)), "null");
    add("proj_element", optI(idx(ELEMENT, p.element)), "null");
    add("proj_pathing", optI(idx(PATHING, p.pathing)), "null");
    add("proj_impact", optI(idx(IMPACT, p.impact)), "null");
    add("proj_count_set", optF(p.count), "null");
    add("proj_range_px_set", optF(p.rangePx), "null");
    add("proj_gravity_scale_set", optF(p.gravityScale), "null");
    add("proj_homing_strength_set", optF(p.homingStrength), "null");
    add("proj_acceleration_mul_set", optF(p.accelerationMultiplier), "null");
    add("proj_bounces_set", optF(p.bounces), "null");
    add("proj_impact_radius_set", optF(p.impactRadiusPx), "null");
    add("proj_pierce_count_set", optF(p.pierceCount), "null");
    add("proj_split_count_set", optF(p.splitCount), "null");
    add("proj_slow_mul_set", optF(p.slowMultiplier), "null");
  }
  const body = parts.length ? ` ${parts.join(", ")} ` : "";
  return `    .{ .id = "${id}", .mod = .{${body}} },`;
}

const sw = starterWeapon;
const swp = sw.projectile;
const rows = crystalRoundsCards
  .filter((c) => c.modifier)
  .map((c) => cardLiteral(c.id, c.modifier!))
  .join("\n");

const out = `// GENERATED by sim/tools/gen_card_data.ts — DO NOT EDIT.
// Source of truth: client/src/sim/data/cards.ts + weapons.ts.
// Mirrors weaponBuild.ts createWeaponBuild/applyCard/mergeProjectileModifier.

pub const CardMod = struct {
    damage_mul: f64 = 1,
    fire_rate_mul: f64 = 1,
    projectile_speed_mul: f64 = 1,
    spread_radians_add: f64 = 0,
    spread_radians_set: ?f64 = null,
    max_health_add: f64 = 0,
    move_speed_mul: f64 = 1,
    parry_cover_mul: f64 = 1,
    parry_cooldown_mul: f64 = 1,
    gravity_mul: f64 = 1,
    shield_charge_mul: f64 = 1,
    shield_recharge_mul: f64 = 1,
    jump_mul: f64 = 1,
    wall_jump_mul: f64 = 1,
    wall_slide_mul: f64 = 1,
    air_jumps_add: f64 = 0,
    dash_charges_add: f64 = 0,
    mirror_shield: bool = false,
    directional_shield: bool = false,
    proj_count_add: f64 = 0,
    proj_bounce_add: f64 = 0,
    proj_split_add: f64 = 0,
    proj_homing_add: f64 = 0,
    proj_speed_mul: f64 = 1,
    proj_size_mul: f64 = 1,
    proj_lifetime_mul: f64 = 1,
    proj_shape: ?u8 = null,
    proj_element: ?u8 = null,
    proj_pathing: ?u8 = null,
    proj_impact: ?u8 = null,
    proj_count_set: ?f64 = null,
    proj_range_px_set: ?f64 = null,
    proj_gravity_scale_set: ?f64 = null,
    proj_homing_strength_set: ?f64 = null,
    proj_acceleration_mul_set: ?f64 = null,
    proj_bounces_set: ?f64 = null,
    proj_impact_radius_set: ?f64 = null,
    proj_pierce_count_set: ?f64 = null,
    proj_split_count_set: ?f64 = null,
    proj_slow_mul_set: ?f64 = null,
};

pub const CardEntry = struct { id: []const u8, mod: CardMod };

/// Starter-pistol base (the only weapon) — mirrors weapons.ts.
pub const StarterBase = struct {
    pub const damage: f64 = ${f(sw.damage, 0)};
    pub const fire_rate: f64 = ${f(sw.fireRate, 0)};
    pub const projectile_speed: f64 = ${f(sw.projectileSpeed, 0)};
    pub const projectile_lifetime_seconds: f64 = ${f(sw.projectileLifetimeSeconds, 0)};
    pub const spread_radians: f64 = ${f(sw.spreadRadians, 0)};
    pub const p_shape: u8 = ${idx(SHAPE, swp.shape)};
    pub const p_count: f64 = ${f(swp.count, 0)};
    pub const p_range_px: f64 = ${f(swp.rangePx, 0)};
    pub const p_speed_mul: f64 = ${f(swp.speedMultiplier, 1)};
    pub const p_size_mul: f64 = ${f(swp.sizeMultiplier, 1)};
    pub const p_pathing: u8 = ${idx(PATHING, swp.pathing)};
    pub const p_element: u8 = ${idx(ELEMENT, swp.element)};
    pub const p_impact: u8 = ${idx(IMPACT, swp.impact)};
    pub const p_lifetime_mul: f64 = ${f(swp.lifetimeMultiplier, 1)};
    pub const p_gravity_scale: f64 = ${f(swp.gravityScale, 0)};
    pub const p_homing_strength: f64 = ${f(swp.homingStrength, 0)};
    pub const p_acceleration_mul: f64 = ${f(swp.accelerationMultiplier, 0)};
    pub const p_bounces: f64 = ${f(swp.bounces, 0)};
    pub const p_impact_radius: f64 = ${f(swp.impactRadiusPx, 0)};
    pub const p_pierce_count: f64 = ${f(swp.pierceCount, 0)};
    pub const p_split_count: f64 = ${f(swp.splitCount, 0)};
    pub const p_slow_mul: f64 = ${f(swp.slowMultiplier, 1)};
};

pub const cards = [_]CardEntry{
${rows}
};

pub fn cardMod(id: []const u8) ?CardMod {
    for (cards) |c| {
        if (std.mem.eql(u8, c.id, id)) return c.mod;
    }
    return null;
}

const std = @import("std");
`;

writeFileSync(resolve(import.meta.dir, "../src/data/cards_gen.zig"), out);
console.log(`cards_gen.zig: ${crystalRoundsCards.filter((c) => c.modifier).length} cards`);
