// Codegen: TS named-map data → sim/src/data/maps_gen.zig.
//
// gospel N-MAP, as RE-SCOPED: the arena GENERATOR is already in Zig
// (map_gen.zig), so every `gen:N` arena is core-native today. What was not
// native is the NAMED maps — boxworks-tower, vessel-nexus, skyseam,
// boxworks-practice and friends live only as TS data, so nothing native can
// construct them. That is what blocks native world-init for 5 of the 10
// archived replays and what N2 offline needs for its non-generated arenas.
//
// Codegen rather than a hand-port, for the same reason gen_card_data.ts
// exists: the TS files stay the single source of truth (the editor, the
// renderer and the server all read them), and a hand-copied Zig mirror
// would drift silently the first time someone nudges a platform. Re-run
// with `bun run gen:maps`.
//
// What crosses: geometry the SIM needs — arena size, spawns, platform AABBs
// and their one-way flags, slopes, launch pads. What does NOT cross:
// destructibles (host-seeded per match, not static geometry), pickups
// (spawned by the host), names and theme keys beyond the theme index, and
// anything purely presentational.

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { MapDefinition } from "../../client/src/sim/types.ts";
import { boxworksTower } from "../../client/src/sim/data/boxworks-tower.ts";
import { vesselNexus } from "../../client/src/sim/data/vessel-nexus.ts";
import { skyseam } from "../../client/src/sim/data/skyseam.ts";
import { boxworksPractice } from "../../client/src/sim/data/boxworks-practice.ts";
import { boxworks } from "../../client/src/sim/data/boxworks.ts";
import { boxworksMini } from "../../client/src/sim/data/boxworks-mini.ts";

// Mirrors collision.ts's ONE_WAY_MAX_HEIGHT_PX and map_gen.zig's
// ONE_WAY_MAX_HEIGHT. Asserted below rather than trusted.
const ONE_WAY_MAX_HEIGHT_PX = 24;

// Mirrors MapDefinition["arenaTheme"] order. Index 0 is the documented
// default for maps that omit the field.
const THEMES = [
  "voidVessel",
  "crystalDock",
  "autogenesHull",
  "jadeIsles",
  "ivoryClouds",
  "hangingWood",
] as const;

const MAPS: MapDefinition[] = [
  boxworks,
  boxworksMini,
  boxworksTower,
  boxworksPractice,
  vesselNexus,
  skyseam,
];

/** Zig identifier for a map id ("boxworks-tower" → "boxworks_tower"). */
const zigName = (id: string): string => id.replace(/[^a-zA-Z0-9]/g, "_");

const f = (n: number): string => (Number.isInteger(n) ? `${n}` : `${n}`);

let out = `// GENERATED by sim/tools/gen_map_data.ts — DO NOT EDIT.
// Source of truth: client/src/sim/data/{boxworks,boxworks-mini,boxworks-tower,
// boxworks-practice,vessel-nexus,skyseam}.ts. Re-run: \`bun run gen:maps\`.
//
// gospel N-MAP. Only SIM-relevant geometry crosses: arena size, spawns,
// platform AABBs (converted from TS centre+size to corner+size, matching
// collision.ts's platformToAABB) and one-way flags, plus slopes and launch
// pads. Destructibles and pickups are host-seeded per match, not static
// geometry, so they stay out — a named map here is the same thing
// world_state_generate_arena produces for a gen:N seed, nothing more.

const collision = @import("../collision.zig");

/// One-way rule, mirrored from collision.ts's buildStaticCache:
/// \`kind === "platform" && size.y <= 24\`. Floors and walls are always
/// solid regardless of height, and a tall "platform" is chest-high cover
/// meant to be solid 4-way.
pub const ONE_WAY_MAX_HEIGHT: f64 = ${ONE_WAY_MAX_HEIGHT_PX};

pub const Spawn = struct { x: f64, y: f64 };

/// Mirrors TS SlopeDefinition exactly (base corner, horizontal run, blessed
/// grade, ascent direction) rather than pre-converting to endpoints — the
/// sim resolves slopes from these fields, and a codegen that "helpfully"
/// converts would be the one place the two representations could disagree.
pub const Slope = struct { base_x: f64, base_y: f64, run: f64, grade_t: f64, dir: f64 };

pub const LaunchPad = struct { x: f64, y: f64, w: f64, h: f64, ix: f64, iy: f64 };

pub const NamedMap = struct {
    id: []const u8,
    width: f64,
    height: f64,
    theme_id: u32,
    statics: []const collision.AABB,
    one_way: []const u8,
    spawns: []const Spawn,
    slopes: []const Slope,
    launch_pads: []const LaunchPad,
};

`;

let assertions = 0;
for (const m of MAPS) {
  const name = zigName(m.id);
  const themeIdx = m.arenaTheme ? THEMES.indexOf(m.arenaTheme) : 0;
  if (themeIdx < 0) throw new Error(`${m.id}: unknown arenaTheme ${m.arenaTheme}`);

  const statics = m.platforms.map((p) => ({
    x: p.position.x - p.size.x / 2,
    y: p.position.y - p.size.y / 2,
    w: p.size.x,
    h: p.size.y,
    oneWay: p.kind === "platform" && p.size.y <= ONE_WAY_MAX_HEIGHT_PX ? 1 : 0,
  }));
  assertions += statics.length;

  out += `pub const ${name}_statics = [_]collision.AABB{\n`;
  for (const s of statics) {
    out += `    .{ .x = ${f(s.x)}, .y = ${f(s.y)}, .w = ${f(s.w)}, .h = ${f(s.h)} },\n`;
  }
  out += `};\n`;
  out += `pub const ${name}_one_way = [_]u8{ ${statics.map((s) => s.oneWay).join(", ")} };\n`;
  out += `pub const ${name}_spawns = [_]Spawn{ ${m.spawns
    .map((s) => `.{ .x = ${f(s.x)}, .y = ${f(s.y)} }`)
    .join(", ")} };\n`;
  out += `pub const ${name}_slopes = [_]Slope{ ${(m.slopes ?? [])
    .map(
      (s) =>
        `.{ .base_x = ${f(s.base.x)}, .base_y = ${f(s.base.y)}, .run = ${f(s.run)}, ` +
        `.grade_t = ${s.grade === "1:1" ? "1" : "0.5"}, .dir = ${s.dir} }`,
    )
    .join(", ")} };\n`;
  out += `pub const ${name}_pads = [_]LaunchPad{ ${(m.launchPads ?? [])
    .map(
      (p) =>
        `.{ .x = ${f(p.position.x - p.size.x / 2)}, .y = ${f(p.position.y - p.size.y / 2)}, .w = ${f(p.size.x)}, .h = ${f(p.size.y)}, .ix = ${f(p.impulse.x)}, .iy = ${f(p.impulse.y)} }`,
    )
    .join(", ")} };\n\n`;
}

out += `pub const NAMED_MAPS = [_]NamedMap{\n`;
for (const m of MAPS) {
  const name = zigName(m.id);
  const themeIdx = m.arenaTheme ? THEMES.indexOf(m.arenaTheme) : 0;
  out += `    .{
        .id = "${m.id}",
        .width = ${f(m.size.x)},
        .height = ${f(m.size.y)},
        .theme_id = ${themeIdx},
        .statics = &${name}_statics,
        .one_way = &${name}_one_way,
        .spawns = &${name}_spawns,
        .slopes = &${name}_slopes,
        .launch_pads = &${name}_pads,
    },\n`;
}
out += `};\n\n`;

out += `/// Look a map up by its wire id. Returns null for an unknown id rather
/// than a default map — silently substituting geometry would desync a
/// replay instead of failing it.
pub fn findNamedMap(id: []const u8) ?*const NamedMap {
    for (&NAMED_MAPS) |*m| {
        if (std.mem.eql(u8, m.id, id)) return m;
    }
    return null;
}

const std = @import("std");
`;

const dest = resolve(import.meta.dir, "../src/data/maps_gen.zig");
writeFileSync(dest, out);
console.log(
  `[gen:maps] wrote ${dest} — ${MAPS.length} maps, ${assertions} platforms`,
);
for (const m of MAPS) {
  console.log(
    `  ${m.id.padEnd(20)} ${m.platforms.length} platforms  ${m.spawns.length} spawns  ` +
      `${(m.slopes ?? []).length} slopes  ${(m.launchPads ?? []).length} pads`,
  );
}
