// GENERATED by sim/tools/gen_card_data.ts — DO NOT EDIT.
// Source of truth: client/src/sim/data/cards.ts + weapons.ts.
// Mirrors weaponBuild.ts createWeaponBuild/applyCard/mergeProjectileModifier.

pub const CardMod = struct {
    damage_mul: f64 = 1,
    fire_rate_mul: f64 = 1,
    projectile_speed_mul: f64 = 1,
    spread_radians_add: f64 = 0,
    spread_radians_set: ?f64 = null,
    max_health_add: f64 = 0,
    move_speed_mul: f64 = 1,
    parry_cover_mul: f64 = 1,
    parry_cooldown_mul: f64 = 1,
    gravity_mul: f64 = 1,
    shield_charge_mul: f64 = 1,
    shield_recharge_mul: f64 = 1,
    jump_mul: f64 = 1,
    wall_jump_mul: f64 = 1,
    wall_slide_mul: f64 = 1,
    air_jumps_add: f64 = 0,
    dash_charges_add: f64 = 0,
    dash_cooldown_mul: f64 = 1,
    mirror_shield: bool = false,
    directional_shield: bool = false,
    delivery: ?u8 = null,
    proj_count_add: f64 = 0,
    proj_bounce_add: f64 = 0,
    proj_split_add: f64 = 0,
    proj_homing_add: f64 = 0,
    proj_speed_mul: f64 = 1,
    proj_size_mul: f64 = 1,
    proj_lifetime_mul: f64 = 1,
    proj_shape: ?u8 = null,
    proj_element: ?u8 = null,
    proj_pathing: ?u8 = null,
    proj_impact: ?u8 = null,
    proj_count_set: ?f64 = null,
    proj_range_px_set: ?f64 = null,
    proj_gravity_scale_set: ?f64 = null,
    proj_homing_strength_set: ?f64 = null,
    proj_acceleration_mul_set: ?f64 = null,
    proj_bounces_set: ?f64 = null,
    proj_impact_radius_set: ?f64 = null,
    proj_pierce_count_set: ?f64 = null,
    proj_split_count_set: ?f64 = null,
    proj_slow_mul_set: ?f64 = null,
};

/// Class-exclusive gate (cardTypes.ts's ClassId — dev-id vocabulary, never
/// the display persona name: wizard/ninja/paladin/priest).
pub const ClassId = enum(u8) {
    wizard = 0,
    ninja = 1,
    paladin = 2,
    priest = 3,
};

/// Draft-weighting tier (cardTypes.ts's CardDefinition.rarity union).
pub const Rarity = enum(u8) {
    common = 0,
    uncommon = 1,
    rare = 2,
    legendary = 3,
    cursed = 4,
};

/// Drafted-active identity tag (cardTypes.ts's AbilityKind union) — a plain
/// identity enum, NOT a struct: it tells a future resolver WHICH ability a
/// card grants, carrying no behavior of its own. Re-derive this list from
/// the live cardTypes.ts union on every future edit (gen_card_data.ts's
/// ABILITY_KIND array is the single source for member order/count).
pub const AbilityKind = enum(u8) {
    crimson_tithe = 0,
    shelter_seal = 1,
    shadow_step = 2,
    veil_of_nought = 3,
    severing_answer = 4,
    sunlance = 5,
    facet_break = 6,
    prism_fan = 7,
    lattice = 8,
    return_glass = 9,
    hard_aperture = 10,
    overclock = 11,
    measure = 12,
    slip_node = 13,
    recoil_step = 14,
    unbroken_seal = 15,
    sunspike = 16,
    judgment_line = 17,
    bastion_pulse = 18,
    aegis_share = 19,
    plant_charge = 20,
    shock_ring = 21,
    rally_light = 22,
    kindled_resolve = 23,
    bulwark_step = 24,
    bleed_tithe = 25,
    severance = 26,
    borrowed_time = 27,
    focus_hex = 28,
    contagion = 29,
    flock_pulse = 30,
    self_lattice = 31,
    glass_ward = 32,
    haste_gift = 33,
    drift_step = 34,
    undercut = 35,
    edge_storm = 36,
    needle = 37,
    read_mark = 38,
    shard_ring = 39,
    wall_bloom = 40,
    ghost_guard = 41,
    second_wind = 42,
    razor_route = 43,
    paper_double = 44,
};

/// One drafted active's timing (cardTypes.ts's AbilityActiveSpec). Paired
/// onto a CardMeta only when the card actually has `active` — see
/// CardMeta.active below.
pub const CardActive = struct {
    kind: AbilityKind,
    cooldown_ms: f64,
    /// Effect window; null = instant (mirrors AbilityActiveSpec.durationMs
    /// being omitted — "omitted = instant" per its own TS doc comment).
    duration_ms: ?f64 = null,
};

/// Mirrors cardTypes.ts's WeaponBucket union — one bool per bucket, a
/// card may belong to several (e.g. `["shape", "trajectory"]`). Only
/// consumer today (Phase 2, docs/zig-step-world-parity-goal.md): the
/// draft/offer-roll's catch-up weighting (draftWeights.ts's
/// `weightForCard`) boosts impact/utility/element/ability-bucket cards
/// for non-winner seats. A packed bool struct, not a `[]const WeaponBucket`
/// slice, because CardMeta (unlike ProjectileEntity et al.) is a plain
/// (non-`extern`) struct living entirely Zig-side (see CardMeta's own doc
/// comment) — a fixed 1-byte bitset is simpler than a slice here and needs
/// no backing array.
pub const CardBuckets = packed struct(u8) {
    delivery: bool = false,
    shape: bool = false,
    trajectory: bool = false,
    quantity: bool = false,
    impact: bool = false,
    element: bool = false,
    utility: bool = false,
    ability: bool = false,
};

/// A card's own identity/metadata — classId/unique/maxStacks/rarity/active.
/// Deliberately a SIBLING struct to CardMod, not an extension of it: CardMod
/// is "the resolved WEAPON stat effect" (damage/speed/spread/... multipliers
/// that fold additively/multiplicatively across a whole hand via
/// weapon_build.zig's resolveMods loop); CardMeta is per-card identity that
/// never folds — it's read once per card, not accumulated across a hand.
/// Cramming classId/active into CardMod would force every hand-resolution
/// call site to start ignoring fields that make no sense to accumulate,
/// which is exactly the kind of accidental-coupling CardMod's own doc
/// comment ("the resolved weapon stat effect") warns against.
pub const CardMeta = struct {
    /// Class-EXCLUSIVE gate (cardTypes.ts's CardDefinition.classId) — null
    /// means universal (every six-axes class-blind card, and every
    /// universal weapon-stat card). Mirrors CardMod's own `?u8`-family
    /// "genuinely absent" convention (this file's established idiom for
    /// optional TS fields), rather than world_state.zig's has_-bool-gate
    /// pattern — that pattern exists because world_state.zig's structs are
    /// `extern` (crossing the wasm ABI boundary), where Zig's tagged
    /// optionals aren't layout-stable. CardMeta/CardEntry never cross that
    /// boundary (weapon_build.zig consumes them Zig-side only), so a plain
    /// `?ClassId` is both idiomatic and consistent with CardMod's own
    /// sibling fields in this exact file.
    class_id: ?ClassId = null,
    /// Can only ever be held once (cardTypes.ts's CardDefinition.unique) —
    /// enforced at the offer-roll and apply-time gates (round.ts / weaponBuild.ts),
    /// not here; this struct only carries the fact.
    unique: bool = false,
    /// Explicit stacking cap (cardTypes.ts's CardDefinition.maxStacks).
    /// 0 = no explicit cap (the TS field is simply absent — stacking is
    /// then gated ONLY by `unique`, or fully unlimited if unique is also
    /// false). Every real maxStacks value in cards.ts is >=1 (see
    /// gen_card_data.ts's assertKnown-adjacent guard), so 0 is an
    /// unambiguous "unset" sentinel — chosen over `?u8` to keep this one
    /// field a plain int (every OTHER CardMeta field already needed either
    /// a bool or an optional-of-a-non-trivial-type; this is the one place a
    /// sentinel reads clearer than an extra optional wrapper).
    max_stacks: u8 = 0,
    /// Draft-weighting tier (cardTypes.ts's CardDefinition.rarity) — always
    /// explicitly set by the generator (every CardDefinition has a required
    /// rarity); the default below is never relied upon, only present so
    /// CardMeta stays a valid zero-initializable struct like CardMod.
    rarity: Rarity = .common,
    /// Weapon-bucket membership (cardTypes.ts's CardDefinition.buckets ??
    /// []) — every real card in cards.ts sets at least one bucket, but the
    /// default here is the honest empty-set, same "never relied upon"
    /// caveat as `rarity`'s default above.
    buckets: CardBuckets = .{},
    /// The ability this card grants, if any (cardTypes.ts's
    /// CardDefinition.active). null = this card has no active — either a
    /// pure weapon-stat card, or (today) not yet authored. Resolution of
    /// WHAT an active does is explicitly out of scope here; this only
    /// carries kind + cooldown/duration identity.
    active: ?CardActive = null,
};

pub const CardEntry = struct { id: []const u8, mod: CardMod, meta: CardMeta };

/// Starter-pistol base (the only weapon) — mirrors weapons.ts.
pub const StarterBase = struct {
    pub const delivery: u8 = 1;
    pub const damage: f64 = 12.0;
    pub const fire_rate: f64 = 4.0;
    pub const projectile_speed: f64 = 650.0;
    pub const projectile_lifetime_seconds: f64 = 1.2;
    pub const spread_radians: f64 = 0.03;
    pub const p_shape: u8 = 3;
    pub const p_count: f64 = 1.0;
    pub const p_range_px: f64 = 720.0;
    pub const p_speed_mul: f64 = 1.0;
    pub const p_size_mul: f64 = 1.0;
    pub const p_pathing: u8 = 0;
    pub const p_element: u8 = 0;
    pub const p_impact: u8 = 0;
    pub const p_lifetime_mul: f64 = 1.0;
    pub const p_gravity_scale: f64 = 0.0;
    pub const p_homing_strength: f64 = 0.0;
    pub const p_acceleration_mul: f64 = 0.0;
    pub const p_bounces: f64 = 0.0;
    pub const p_impact_radius: f64 = 0.0;
    pub const p_pierce_count: f64 = 0.0;
    pub const p_split_count: f64 = 0.0;
    pub const p_slow_mul: f64 = 1.0;
};

pub const cards = [_]CardEntry{
    .{ .id = "raycast-prism", .mod = .{ .damage_mul = 0.9, .delivery = 1, .proj_range_px_set = 880.0, .proj_impact_radius_set = 12.0 }, .meta = .{ .unique = true, .rarity = .rare, .buckets = .{ .delivery = true } } },
    .{ .id = "crystal-volley", .mod = .{ .damage_mul = 1.06, .delivery = 0, .proj_speed_mul = 1.06, .proj_shape = 3, .proj_count_set = 1.0 }, .meta = .{ .unique = true, .rarity = .common, .buckets = .{ .delivery = true } } },
    .{ .id = "circle-rounds", .mod = .{ .projectile_speed_mul = 1.1, .delivery = 0, .proj_size_mul = 0.92, .proj_shape = 0, .proj_range_px_set = 480.0 }, .meta = .{ .unique = true, .rarity = .common, .buckets = .{ .shape = true } } },
    .{ .id = "triangle-rounds", .mod = .{ .projectile_speed_mul = 0.95, .delivery = 0, .proj_lifetime_mul = 1.4, .proj_shape = 1, .proj_range_px_set = 1080.0 }, .meta = .{ .unique = true, .rarity = .common, .buckets = .{ .shape = true } } },
    .{ .id = "square-rounds", .mod = .{ .projectile_speed_mul = 0.8, .proj_size_mul = 1.3, .proj_shape = 2 }, .meta = .{ .unique = true, .rarity = .uncommon, .buckets = .{ .shape = true } } },
    .{ .id = "x-rounds", .mod = .{ .fire_rate_mul = 0.92, .projectile_speed_mul = 0.9, .proj_size_mul = 1.55, .proj_shape = 5 }, .meta = .{ .unique = true, .rarity = .uncommon, .buckets = .{ .shape = true } } },
    .{ .id = "i-rounds", .mod = .{ .projectile_speed_mul = 0.78, .proj_lifetime_mul = 1.15, .proj_shape = 6, .proj_pathing = 7, .proj_acceleration_mul_set = 1.4 }, .meta = .{ .unique = true, .rarity = .uncommon, .buckets = .{ .shape = true, .trajectory = true } } },
    .{ .id = "orby-blap-blap", .mod = .{ .damage_mul = 0.78, .projectile_speed_mul = 0.72, .spread_radians_set = 0.3141592653589793, .proj_size_mul = 1.38, .proj_shape = 4, .proj_count_set = 2.0, .proj_impact_radius_set = 36.0 }, .meta = .{ .unique = true, .rarity = .rare, .buckets = .{ .shape = true, .quantity = true } } },
    .{ .id = "continuous-refractor", .mod = .{ .damage_mul = 0.42, .fire_rate_mul = 2.4, .delivery = 2, .proj_impact = 4, .proj_range_px_set = 760.0, .proj_slow_mul_set = 0.72 }, .meta = .{ .unique = true, .rarity = .rare, .buckets = .{ .delivery = true } } },
    .{ .id = "shard-bloom", .mod = .{ .damage_mul = 0.62, .fire_rate_mul = 0.82, .spread_radians_add = 0.6632251157578452, .delivery = 0, .proj_count_add = 5.0, .proj_size_mul = 0.78, .proj_range_px_set = 390.0 }, .meta = .{ .max_stacks = 2, .rarity = .rare, .buckets = .{ .quantity = true } } },
    .{ .id = "arc-shards", .mod = .{ .projectile_speed_mul = 0.86, .proj_pathing = 1, .proj_gravity_scale_set = 560.0 }, .meta = .{ .rarity = .common, .buckets = .{ .trajectory = true } } },
    .{ .id = "deadfall-mortar", .mod = .{ .fire_rate_mul = 0.8, .projectile_speed_mul = 0.6, .proj_size_mul = 1.15, .proj_pathing = 1, .proj_impact = 1, .proj_gravity_scale_set = 2100.0, .proj_impact_radius_set = 82.0 }, .meta = .{ .unique = true, .rarity = .rare, .buckets = .{ .trajectory = true, .impact = true } } },
    .{ .id = "seeker-facets", .mod = .{ .projectile_speed_mul = 0.82, .delivery = 0, .proj_homing_add = 1.2, .proj_pathing = 4, .proj_homing_strength_set = 4.4 }, .meta = .{ .max_stacks = 4, .rarity = .rare, .buckets = .{ .trajectory = true } } },
    .{ .id = "micro-seekers", .mod = .{ .damage_mul = 0.78, .projectile_speed_mul = 0.9, .spread_radians_add = 0.2792526803190927, .proj_count_add = 2.0, .proj_homing_add = 0.9, .proj_size_mul = 0.74, .proj_pathing = 4, .proj_homing_strength_set = 3.2 }, .meta = .{ .max_stacks = 5, .rarity = .uncommon, .buckets = .{ .trajectory = true, .quantity = true } } },
    .{ .id = "bouncy-prism", .mod = .{ .proj_bounce_add = 4.0, .proj_pathing = 2 }, .meta = .{ .max_stacks = 4, .rarity = .uncommon, .buckets = .{ .trajectory = true } } },
    .{ .id = "extra-bounce", .mod = .{ .proj_bounce_add = 1.0, .proj_pathing = 2 }, .meta = .{ .max_stacks = 8, .rarity = .common, .buckets = .{ .trajectory = true } } },
    .{ .id = "boomerang-return", .mod = .{ .projectile_speed_mul = 0.92, .proj_lifetime_mul = 1.18, .proj_pathing = 3 }, .meta = .{ .unique = true, .rarity = .uncommon, .buckets = .{ .trajectory = true } } },
    .{ .id = "x-velocity", .mod = .{ .projectile_speed_mul = 1.18, .proj_lifetime_mul = 0.96 }, .meta = .{ .max_stacks = 7, .rarity = .common, .buckets = .{ .trajectory = true } } },
    .{ .id = "falling-star", .mod = .{ .projectile_speed_mul = 1.5, .proj_lifetime_mul = 1.1, .proj_pathing = 7, .proj_acceleration_mul_set = -1.8 }, .meta = .{ .unique = true, .rarity = .rare, .buckets = .{ .trajectory = true } } },
    .{ .id = "zero-g-floaters", .mod = .{ .projectile_speed_mul = 0.58, .proj_size_mul = 1.18, .proj_lifetime_mul = 1.5, .proj_pathing = 6 }, .meta = .{ .unique = true, .rarity = .uncommon, .buckets = .{ .trajectory = true } } },
    .{ .id = "triple-fan", .mod = .{ .damage_mul = 0.74, .spread_radians_add = 0.2792526803190927, .proj_count_add = 2.0, .proj_bounce_add = 2.0, .proj_pathing = 2 }, .meta = .{ .max_stacks = 4, .rarity = .uncommon, .buckets = .{ .quantity = true, .trajectory = true } } },
    .{ .id = "five-shard-spray", .mod = .{ .damage_mul = 0.6, .fire_rate_mul = 0.9, .projectile_speed_mul = 1.22, .spread_radians_add = 0.3490658503988659, .proj_count_add = 4.0, .proj_size_mul = 0.6 }, .meta = .{ .max_stacks = 2, .rarity = .rare, .buckets = .{ .quantity = true } } },
    .{ .id = "one-more-shard", .mod = .{ .damage_mul = 0.94, .spread_radians_add = 0.12217304763960307, .proj_count_add = 1.0 }, .meta = .{ .max_stacks = 8, .rarity = .common, .buckets = .{ .quantity = true } } },
    .{ .id = "wide-barrage", .mod = .{ .damage_mul = 0.7, .fire_rate_mul = 0.94, .spread_radians_add = 0.767944870877505, .proj_count_add = 3.0, .proj_size_mul = 0.82 }, .meta = .{ .max_stacks = 5, .rarity = .uncommon, .buckets = .{ .quantity = true } } },
    .{ .id = "orbiting-satellites", .mod = .{ .fire_rate_mul = 1.12 }, .meta = .{ .unique = true, .rarity = .rare, .buckets = .{ .quantity = true } } },
    .{ .id = "cluster-bomb", .mod = .{ .fire_rate_mul = 0.72, .proj_split_add = 6.0, .proj_size_mul = 1.12 }, .meta = .{ .max_stacks = 3, .rarity = .rare, .buckets = .{ .quantity = true } } },
    .{ .id = "explosive-facet", .mod = .{ .damage_mul = 0.92, .proj_impact = 1, .proj_impact_radius_set = 64.0 }, .meta = .{ .unique = true, .rarity = .uncommon, .buckets = .{ .impact = true } } },
    .{ .id = "sticky-shards", .mod = .{ .projectile_speed_mul = 0.8, .proj_impact = 2, .proj_impact_radius_set = 48.0 }, .meta = .{ .unique = true, .rarity = .uncommon, .buckets = .{ .impact = true } } },
    .{ .id = "pierce-chain", .mod = .{ .proj_impact = 3, .proj_pierce_count_set = 3.0, .proj_split_count_set = 2.0 }, .meta = .{ .unique = true, .rarity = .rare, .buckets = .{ .impact = true } } },
    .{ .id = "slow-field", .mod = .{ .damage_mul = 0.86, .proj_impact = 4, .proj_impact_radius_set = 70.0, .proj_slow_mul_set = 0.58 }, .meta = .{ .unique = true, .rarity = .uncommon, .buckets = .{ .impact = true } } },
    .{ .id = "molten-core", .mod = .{ .proj_element = 2, .proj_impact_radius_set = 42.0 }, .meta = .{ .unique = true, .rarity = .uncommon, .buckets = .{ .element = true } } },
    .{ .id = "frost-prism", .mod = .{ .proj_element = 3, .proj_impact = 4, .proj_slow_mul_set = 0.68 }, .meta = .{ .unique = true, .rarity = .uncommon, .buckets = .{ .element = true } } },
    .{ .id = "voltaic-spark", .mod = .{ .projectile_speed_mul = 1.08, .proj_element = 4, .proj_impact = 3, .proj_pierce_count_set = 1.0 }, .meta = .{ .unique = true, .rarity = .rare, .buckets = .{ .element = true } } },
    .{ .id = "void-fracture", .mod = .{ .damage_mul = 1.08, .proj_element = 5, .proj_pierce_count_set = 2.0 }, .meta = .{ .unique = true, .rarity = .rare, .buckets = .{ .element = true } } },
    .{ .id = "radiant-overload", .mod = .{ .damage_mul = 1.14, .fire_rate_mul = 0.82, .proj_size_mul = 1.14, .proj_element = 6, .proj_impact_radius_set = 58.0 }, .meta = .{ .unique = true, .rarity = .rare, .buckets = .{ .element = true } } },
    .{ .id = "rapid-refraction", .mod = .{ .fire_rate_mul = 1.22, .projectile_speed_mul = 1.06, .proj_size_mul = 0.88 }, .meta = .{ .max_stacks = 5, .rarity = .common, .buckets = .{ .utility = true } } },
    .{ .id = "needle-compressor", .mod = .{ .fire_rate_mul = 1.14, .proj_size_mul = 0.86 }, .meta = .{ .max_stacks = 5, .rarity = .common, .buckets = .{ .utility = true } } },
    .{ .id = "heavy-coolant", .mod = .{ .fire_rate_mul = 0.88, .proj_size_mul = 1.22 }, .meta = .{ .max_stacks = 6, .rarity = .common, .buckets = .{ .utility = true } } },
    .{ .id = "essence-battery", .mod = .{ .proj_size_mul = 1.1, .proj_element = 0 }, .meta = .{ .max_stacks = 4, .rarity = .common, .buckets = .{ .utility = true } } },
    .{ .id = "crystal-plating", .mod = .{ .max_health_add = 20.0, .move_speed_mul = 0.98, .proj_size_mul = 1.14, .proj_shape = 3, .proj_element = 0 }, .meta = .{ .max_stacks = 5, .rarity = .common, .buckets = .{ .utility = true } } },
    .{ .id = "wide-parry", .mod = .{ .parry_cover_mul = 1.28, .proj_size_mul = 1.04, .proj_element = 0 }, .meta = .{ .max_stacks = 2, .rarity = .uncommon, .buckets = .{ .utility = true } } },
    .{ .id = "quick-parry", .mod = .{ .dash_cooldown_mul = 0.86, .proj_speed_mul = 1.06, .proj_size_mul = 0.94, .proj_shape = 2 }, .meta = .{ .max_stacks = 2, .rarity = .uncommon, .buckets = .{ .utility = true } } },
    .{ .id = "overcharge", .mod = .{ .fire_rate_mul = 0.72, .proj_size_mul = 1.42, .proj_impact_radius_set = 76.0 }, .meta = .{ .unique = true, .rarity = .rare, .buckets = .{ .utility = true } } },
    .{ .id = "mirror-shield", .mod = .{ .mirror_shield = true, .proj_element = 0 }, .meta = .{ .unique = true, .rarity = .rare, .buckets = .{ .utility = true } } },
    .{ .id = "cataclysmic-prism", .mod = .{ .damage_mul = 1.18, .fire_rate_mul = 0.72, .proj_size_mul = 1.22, .proj_element = 6, .proj_impact = 1, .proj_impact_radius_set = 118.0 }, .meta = .{ .unique = true, .rarity = .legendary, .buckets = .{ .impact = true, .element = true } } },
    .{ .id = "homing-cluster", .mod = .{ .damage_mul = 0.78, .projectile_speed_mul = 0.82, .spread_radians_set = 0.4886921905584123, .proj_pathing = 4, .proj_count_set = 3.0, .proj_homing_strength_set = 5.2 }, .meta = .{ .unique = true, .rarity = .legendary, .buckets = .{ .trajectory = true, .quantity = true } } },
    .{ .id = "sticky-ray", .mod = .{ .fire_rate_mul = 0.78, .delivery = 1, .proj_element = 0, .proj_impact = 2, .proj_impact_radius_set = 74.0 }, .meta = .{ .unique = true, .rarity = .legendary, .buckets = .{ .delivery = true, .impact = true } } },
    .{ .id = "sprint-coils", .mod = .{ .move_speed_mul = 1.18 }, .meta = .{ .max_stacks = 3, .rarity = .uncommon, .buckets = .{ .utility = true } } },
    .{ .id = "glide-membrane", .mod = .{ .gravity_mul = 0.74 }, .meta = .{ .max_stacks = 2, .rarity = .uncommon, .buckets = .{ .utility = true } } },
    .{ .id = "lead-boots", .mod = .{ .move_speed_mul = 1.06, .gravity_mul = 1.35 }, .meta = .{ .max_stacks = 2, .rarity = .uncommon, .buckets = .{ .utility = true } } },
    .{ .id = "spring-heel", .mod = .{ .jump_mul = 1.18, .wall_jump_mul = 1.16 }, .meta = .{ .max_stacks = 2, .rarity = .uncommon, .buckets = .{ .utility = true } } },
    .{ .id = "gecko-grip", .mod = .{ .wall_slide_mul = 0.45 }, .meta = .{ .max_stacks = 2, .rarity = .uncommon, .buckets = .{ .utility = true } } },
    .{ .id = "double-jump", .mod = .{ .air_jumps_add = 1.0 }, .meta = .{ .max_stacks = 3, .rarity = .rare, .buckets = .{ .utility = true } } },
    .{ .id = "blink-dash", .mod = .{ .dash_charges_add = 1.0 }, .meta = .{ .max_stacks = 2, .rarity = .rare, .buckets = .{ .utility = true } } },
    .{ .id = "bulwark-core", .mod = .{ .shield_charge_mul = 1.6, .proj_size_mul = 1.08, .proj_shape = 3 }, .meta = .{ .max_stacks = 3, .rarity = .uncommon, .buckets = .{ .utility = true } } },
    .{ .id = "rapid-capacitor", .mod = .{ .shield_recharge_mul = 1.8, .proj_size_mul = 1.08, .proj_shape = 0 }, .meta = .{ .max_stacks = 3, .rarity = .uncommon, .buckets = .{ .utility = true } } },
    .{ .id = "aim-barrier", .mod = .{ .shield_charge_mul = 2.2, .directional_shield = true }, .meta = .{ .unique = true, .rarity = .rare, .buckets = .{ .utility = true } } },
    .{ .id = "riot-mirror", .mod = .{ .shield_charge_mul = 1.7, .mirror_shield = true, .directional_shield = true, .proj_element = 0 }, .meta = .{ .unique = true, .rarity = .legendary, .buckets = .{ .utility = true } } },
    .{ .id = "stolen-fangs", .mod = .{ .proj_element = 0 }, .meta = .{ .unique = true, .rarity = .legendary, .buckets = .{ .utility = true } } },
    .{ .id = "crimson-tithe", .mod = .{}, .meta = .{ .unique = true, .rarity = .rare, .buckets = .{ .ability = true }, .active = .{ .kind = .crimson_tithe, .cooldown_ms = 14000.0, .duration_ms = 3000.0 } } },
    .{ .id = "shadow-step", .mod = .{}, .meta = .{ .unique = true, .rarity = .rare, .buckets = .{ .ability = true }, .active = .{ .kind = .shadow_step, .cooldown_ms = 9000.0 } } },
    .{ .id = "veil-of-nought", .mod = .{}, .meta = .{ .unique = true, .rarity = .legendary, .buckets = .{ .ability = true }, .active = .{ .kind = .veil_of_nought, .cooldown_ms = 16000.0, .duration_ms = 1500.0 } } },
    .{ .id = "severing-answer", .mod = .{}, .meta = .{ .unique = true, .rarity = .legendary, .buckets = .{ .ability = true }, .active = .{ .kind = .severing_answer, .cooldown_ms = 12000.0, .duration_ms = 500.0 } } },
    .{ .id = "shelter-seal", .mod = .{}, .meta = .{ .unique = true, .rarity = .legendary, .buckets = .{ .ability = true }, .active = .{ .kind = .shelter_seal, .cooldown_ms = 12000.0, .duration_ms = 2500.0 } } },
    .{ .id = "sunlance", .mod = .{}, .meta = .{ .class_id = .wizard, .unique = true, .rarity = .rare, .buckets = .{ .ability = true }, .active = .{ .kind = .sunlance, .cooldown_ms = 7000.0, .duration_ms = 700.0 } } },
    .{ .id = "facet-break", .mod = .{}, .meta = .{ .class_id = .wizard, .unique = true, .rarity = .rare, .buckets = .{ .ability = true }, .active = .{ .kind = .facet_break, .cooldown_ms = 8000.0, .duration_ms = 4000.0 } } },
    .{ .id = "prism-fan", .mod = .{}, .meta = .{ .class_id = .wizard, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .prism_fan, .cooldown_ms = 9000.0 } } },
    .{ .id = "lattice", .mod = .{}, .meta = .{ .class_id = .wizard, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .lattice, .cooldown_ms = 9000.0 } } },
    .{ .id = "return-glass", .mod = .{}, .meta = .{ .class_id = .wizard, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .return_glass, .cooldown_ms = 10000.0 } } },
    .{ .id = "hard-aperture", .mod = .{}, .meta = .{ .class_id = .wizard, .unique = true, .rarity = .rare, .buckets = .{ .ability = true }, .active = .{ .kind = .hard_aperture, .cooldown_ms = 9000.0, .duration_ms = 600.0 } } },
    .{ .id = "overclock", .mod = .{}, .meta = .{ .class_id = .wizard, .unique = true, .rarity = .rare, .buckets = .{ .ability = true }, .active = .{ .kind = .overclock, .cooldown_ms = 10000.0, .duration_ms = 3000.0 } } },
    .{ .id = "measure", .mod = .{}, .meta = .{ .class_id = .wizard, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .measure, .cooldown_ms = 9000.0, .duration_ms = 700.0 } } },
    .{ .id = "slip-node", .mod = .{}, .meta = .{ .class_id = .wizard, .unique = true, .rarity = .rare, .buckets = .{ .ability = true }, .active = .{ .kind = .slip_node, .cooldown_ms = 6000.0 } } },
    .{ .id = "recoil-step", .mod = .{}, .meta = .{ .class_id = .wizard, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .recoil_step, .cooldown_ms = 6000.0, .duration_ms = 1200.0 } } },
    .{ .id = "bastion-pulse", .mod = .{}, .meta = .{ .class_id = .paladin, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .bastion_pulse, .cooldown_ms = 8000.0 } } },
    .{ .id = "sunspike", .mod = .{}, .meta = .{ .class_id = .paladin, .unique = true, .rarity = .rare, .buckets = .{ .ability = true }, .active = .{ .kind = .sunspike, .cooldown_ms = 7000.0 } } },
    .{ .id = "judgment-line", .mod = .{}, .meta = .{ .class_id = .paladin, .unique = true, .rarity = .rare, .buckets = .{ .ability = true }, .active = .{ .kind = .judgment_line, .cooldown_ms = 8000.0, .duration_ms = 3000.0 } } },
    .{ .id = "unbroken-seal", .mod = .{}, .meta = .{ .class_id = .paladin, .unique = true, .rarity = .rare, .buckets = .{ .ability = true }, .active = .{ .kind = .unbroken_seal, .cooldown_ms = 7000.0, .duration_ms = 5000.0 } } },
    .{ .id = "aegis-share", .mod = .{}, .meta = .{ .class_id = .paladin, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .aegis_share, .cooldown_ms = 8000.0, .duration_ms = 3000.0 } } },
    .{ .id = "plant-charge", .mod = .{}, .meta = .{ .class_id = .paladin, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .plant_charge, .cooldown_ms = 6000.0 } } },
    .{ .id = "shock-ring", .mod = .{}, .meta = .{ .class_id = .paladin, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .shock_ring, .cooldown_ms = 9000.0, .duration_ms = 1500.0 } } },
    .{ .id = "rally-light", .mod = .{}, .meta = .{ .class_id = .paladin, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .rally_light, .cooldown_ms = 9000.0, .duration_ms = 5000.0 } } },
    .{ .id = "kindled-resolve", .mod = .{}, .meta = .{ .class_id = .paladin, .unique = true, .rarity = .rare, .buckets = .{ .ability = true }, .active = .{ .kind = .kindled_resolve, .cooldown_ms = 12000.0, .duration_ms = 4000.0 } } },
    .{ .id = "bulwark-step", .mod = .{}, .meta = .{ .class_id = .paladin, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .bulwark_step, .cooldown_ms = 4000.0 } } },
    .{ .id = "bleed-tithe", .mod = .{}, .meta = .{ .class_id = .priest, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .bleed_tithe, .cooldown_ms = 6000.0 } } },
    .{ .id = "severance", .mod = .{}, .meta = .{ .class_id = .priest, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .severance, .cooldown_ms = 7000.0 } } },
    .{ .id = "borrowed-time", .mod = .{}, .meta = .{ .class_id = .priest, .unique = true, .rarity = .rare, .buckets = .{ .ability = true }, .active = .{ .kind = .borrowed_time, .cooldown_ms = 8000.0 } } },
    .{ .id = "focus-hex", .mod = .{}, .meta = .{ .class_id = .priest, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .focus_hex, .cooldown_ms = 6000.0, .duration_ms = 4000.0 } } },
    .{ .id = "contagion", .mod = .{}, .meta = .{ .class_id = .priest, .unique = true, .rarity = .rare, .buckets = .{ .ability = true }, .active = .{ .kind = .contagion, .cooldown_ms = 9000.0 } } },
    .{ .id = "flock-pulse", .mod = .{}, .meta = .{ .class_id = .priest, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .flock_pulse, .cooldown_ms = 7000.0 } } },
    .{ .id = "self-lattice", .mod = .{}, .meta = .{ .class_id = .priest, .unique = true, .rarity = .common, .buckets = .{ .ability = true }, .active = .{ .kind = .self_lattice, .cooldown_ms = 6000.0 } } },
    .{ .id = "glass-ward", .mod = .{}, .meta = .{ .class_id = .priest, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .glass_ward, .cooldown_ms = 7000.0 } } },
    .{ .id = "haste-gift", .mod = .{}, .meta = .{ .class_id = .priest, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .haste_gift, .cooldown_ms = 7000.0, .duration_ms = 5000.0 } } },
    .{ .id = "drift-step", .mod = .{}, .meta = .{ .class_id = .priest, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .drift_step, .cooldown_ms = 6000.0 } } },
    .{ .id = "undercut", .mod = .{}, .meta = .{ .class_id = .ninja, .unique = true, .rarity = .rare, .buckets = .{ .ability = true }, .active = .{ .kind = .undercut, .cooldown_ms = 8000.0, .duration_ms = 4000.0 } } },
    .{ .id = "edge-storm", .mod = .{}, .meta = .{ .class_id = .ninja, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .edge_storm, .cooldown_ms = 8000.0, .duration_ms = 6000.0 } } },
    .{ .id = "needle", .mod = .{}, .meta = .{ .class_id = .ninja, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .needle, .cooldown_ms = 6000.0 } } },
    .{ .id = "read-mark", .mod = .{}, .meta = .{ .class_id = .ninja, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .read_mark, .cooldown_ms = 6000.0, .duration_ms = 5000.0 } } },
    .{ .id = "shard-ring", .mod = .{}, .meta = .{ .class_id = .ninja, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .shard_ring, .cooldown_ms = 7000.0 } } },
    .{ .id = "wall-bloom", .mod = .{}, .meta = .{ .class_id = .ninja, .unique = true, .rarity = .common, .buckets = .{ .ability = true }, .active = .{ .kind = .wall_bloom, .cooldown_ms = 7000.0, .duration_ms = 9000.0 } } },
    .{ .id = "ghost-guard", .mod = .{}, .meta = .{ .class_id = .ninja, .unique = true, .rarity = .rare, .buckets = .{ .ability = true }, .active = .{ .kind = .ghost_guard, .cooldown_ms = 9000.0, .duration_ms = 6000.0 } } },
    .{ .id = "second-wind", .mod = .{}, .meta = .{ .class_id = .ninja, .unique = true, .rarity = .common, .buckets = .{ .ability = true }, .active = .{ .kind = .second_wind, .cooldown_ms = 8000.0, .duration_ms = 1500.0 } } },
    .{ .id = "razor-route", .mod = .{}, .meta = .{ .class_id = .ninja, .unique = true, .rarity = .uncommon, .buckets = .{ .ability = true }, .active = .{ .kind = .razor_route, .cooldown_ms = 7000.0, .duration_ms = 3000.0 } } },
    .{ .id = "paper-double", .mod = .{}, .meta = .{ .class_id = .ninja, .unique = true, .rarity = .rare, .buckets = .{ .ability = true }, .active = .{ .kind = .paper_double, .cooldown_ms = 9000.0 } } },
};

pub fn cardMod(id: []const u8) ?CardMod {
    for (cards) |c| {
        if (std.mem.eql(u8, c.id, id)) return c.mod;
    }
    return null;
}

pub fn cardMeta(id: []const u8) ?CardMeta {
    for (cards) |c| {
        if (std.mem.eql(u8, c.id, id)) return c.meta;
    }
    return null;
}

const std = @import("std");
