// GENERATED by sim/tools/gen_map_data.ts — DO NOT EDIT.
// Source of truth: client/src/sim/data/{boxworks,boxworks-mini,boxworks-tower,
// boxworks-practice,vessel-nexus,skyseam}.ts. Re-run: `bun run gen:maps`.
//
// gospel N-MAP. Only SIM-relevant geometry crosses: arena size, spawns,
// platform AABBs (converted from TS centre+size to corner+size, matching
// collision.ts's platformToAABB) and one-way flags, plus slopes and launch
// pads. Destructibles and pickups are host-seeded per match, not static
// geometry, so they stay out — a named map here is the same thing
// world_state_generate_arena produces for a gen:N seed, nothing more.

const collision = @import("../collision.zig");

/// One-way rule, mirrored from collision.ts's buildStaticCache:
/// `kind === "platform" && size.y <= 24`. Floors and walls are always
/// solid regardless of height, and a tall "platform" is chest-high cover
/// meant to be solid 4-way.
pub const ONE_WAY_MAX_HEIGHT: f64 = 24;

pub const Spawn = struct { x: f64, y: f64 };

/// Mirrors TS SlopeDefinition exactly (base corner, horizontal run, blessed
/// grade, ascent direction) rather than pre-converting to endpoints — the
/// sim resolves slopes from these fields, and a codegen that "helpfully"
/// converts would be the one place the two representations could disagree.
pub const Slope = struct { base_x: f64, base_y: f64, run: f64, grade_t: f64, dir: f64 };

pub const LaunchPad = struct { x: f64, y: f64, w: f64, h: f64, ix: f64, iy: f64 };

pub const NamedMap = struct {
    id: []const u8,
    width: f64,
    height: f64,
    theme_id: u32,
    statics: []const collision.AABB,
    one_way: []const u8,
    spawns: []const Spawn,
    slopes: []const Slope,
    launch_pads: []const LaunchPad,
};

pub const boxworks_statics = [_]collision.AABB{
    .{ .x = 32, .y = 508, .w = 896, .h = 32 },
    .{ .x = 0, .y = 0, .w = 32, .h = 540 },
    .{ .x = 928, .y = 0, .w = 32, .h = 540 },
};
pub const boxworks_one_way = [_]u8{ 0, 0, 0 };
pub const boxworks_spawns = [_]Spawn{ .{ .x = 200, .y = 432 }, .{ .x = 760, .y = 432 }, .{ .x = 240, .y = 264 }, .{ .x = 720, .y = 264 } };
pub const boxworks_slopes = [_]Slope{  };
pub const boxworks_pads = [_]LaunchPad{  };

pub const boxworks_mini_statics = [_]collision.AABB{
    .{ .x = 0, .y = 608, .w = 1280, .h = 32 },
    .{ .x = 0, .y = 0, .w = 32, .h = 640 },
    .{ .x = 1248, .y = 0, .w = 32, .h = 640 },
    .{ .x = 0, .y = 0, .w = 1280, .h = 32 },
    .{ .x = 450, .y = 351, .w = 380, .h = 22 },
    .{ .x = 110, .y = 479, .w = 220, .h = 18 },
    .{ .x = 950, .y = 479, .w = 220, .h = 18 },
    .{ .x = 244, .y = 320, .w = 72, .h = 80 },
    .{ .x = 964, .y = 320, .w = 72, .h = 80 },
};
pub const boxworks_mini_one_way = [_]u8{ 0, 0, 0, 0, 1, 1, 1, 0, 0 };
pub const boxworks_mini_spawns = [_]Spawn{ .{ .x = 160, .y = 540 }, .{ .x = 1120, .y = 540 }, .{ .x = 470, .y = 540 }, .{ .x = 810, .y = 540 }, .{ .x = 220, .y = 420 }, .{ .x = 1060, .y = 420 }, .{ .x = 540, .y = 292 }, .{ .x = 740, .y = 292 } };
pub const boxworks_mini_slopes = [_]Slope{  };
pub const boxworks_mini_pads = [_]LaunchPad{  };

pub const boxworks_tower_statics = [_]collision.AABB{
    .{ .x = 0, .y = 1048, .w = 1440, .h = 32 },
    .{ .x = 0, .y = 0, .w = 32, .h = 1080 },
    .{ .x = 1408, .y = 0, .w = 32, .h = 1080 },
    .{ .x = 0, .y = 0, .w = 1440, .h = 32 },
    .{ .x = 160, .y = 749, .w = 320, .h = 22 },
    .{ .x = 960, .y = 749, .w = 320, .h = 22 },
    .{ .x = 580, .y = 609, .w = 280, .h = 22 },
    .{ .x = 530, .y = 715, .w = 60, .h = 90 },
    .{ .x = 850, .y = 715, .w = 60, .h = 90 },
    .{ .x = 110, .y = 449, .w = 260, .h = 22 },
    .{ .x = 1070, .y = 449, .w = 260, .h = 22 },
    .{ .x = 610, .y = 269, .w = 220, .h = 22 },
    .{ .x = 300, .y = 931, .w = 160, .h = 18 },
    .{ .x = 980, .y = 931, .w = 160, .h = 18 },
};
pub const boxworks_tower_one_way = [_]u8{ 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1 };
pub const boxworks_tower_spawns = [_]Spawn{ .{ .x = 160, .y = 1000 }, .{ .x = 400, .y = 1000 }, .{ .x = 720, .y = 1000 }, .{ .x = 1040, .y = 1000 }, .{ .x = 1280, .y = 1000 }, .{ .x = 280, .y = 690 }, .{ .x = 560, .y = 690 }, .{ .x = 880, .y = 690 }, .{ .x = 1160, .y = 690 }, .{ .x = 400, .y = 480 }, .{ .x = 720, .y = 480 }, .{ .x = 1040, .y = 480 }, .{ .x = 220, .y = 320 }, .{ .x = 1220, .y = 320 }, .{ .x = 560, .y = 200 }, .{ .x = 880, .y = 200 } };
pub const boxworks_tower_slopes = [_]Slope{  };
pub const boxworks_tower_pads = [_]LaunchPad{  };

pub const boxworks_practice_statics = [_]collision.AABB{
    .{ .x = 0, .y = 0, .w = 32, .h = 900 },
    .{ .x = 2568, .y = 0, .w = 32, .h = 900 },
    .{ .x = 0, .y = 0, .w = 2600, .h = 32 },
    .{ .x = 0, .y = 868, .w = 560, .h = 32 },
    .{ .x = 660, .y = 868, .w = 1940, .h = 32 },
    .{ .x = 1060, .y = 218, .w = 40, .h = 650 },
    .{ .x = 1230, .y = 218, .w = 40, .h = 650 },
    .{ .x = 1100, .y = 218, .w = 500, .h = 18 },
    .{ .x = 1940, .y = 218, .w = 400, .h = 18 },
};
pub const boxworks_practice_one_way = [_]u8{ 0, 0, 0, 0, 0, 0, 0, 1, 1 };
pub const boxworks_practice_spawns = [_]Spawn{ .{ .x = 150, .y = 800 } };
pub const boxworks_practice_slopes = [_]Slope{  };
pub const boxworks_practice_pads = [_]LaunchPad{  };

pub const vessel_nexus_statics = [_]collision.AABB{
    .{ .x = 0, .y = 1064, .w = 3000, .h = 36 },
    .{ .x = 0, .y = 0, .w = 32, .h = 1100 },
    .{ .x = 2968, .y = 0, .w = 32, .h = 1100 },
    .{ .x = 50, .y = 0, .w = 700, .h = 32 },
    .{ .x = 2250, .y = 0, .w = 700, .h = 32 },
    .{ .x = 456, .y = 974, .w = 48, .h = 90 },
    .{ .x = 934, .y = 954, .w = 52, .h = 110 },
    .{ .x = 1472, .y = 964, .w = 56, .h = 100 },
    .{ .x = 2014, .y = 954, .w = 52, .h = 110 },
    .{ .x = 2496, .y = 974, .w = 48, .h = 90 },
    .{ .x = 680, .y = 1028, .w = 80, .h = 18 },
    .{ .x = 1215, .y = 1024, .w = 90, .h = 18 },
    .{ .x = 1695, .y = 1024, .w = 90, .h = 18 },
    .{ .x = 2240, .y = 1028, .w = 80, .h = 18 },
    .{ .x = 220, .y = 956, .w = 280, .h = 18 },
    .{ .x = 780, .y = 956, .w = 240, .h = 18 },
    .{ .x = 1340, .y = 956, .w = 320, .h = 18 },
    .{ .x = 1980, .y = 956, .w = 240, .h = 18 },
    .{ .x = 2500, .y = 956, .w = 280, .h = 18 },
    .{ .x = 390, .y = 848, .w = 220, .h = 18 },
    .{ .x = 1270, .y = 848, .w = 260, .h = 18 },
    .{ .x = 2400, .y = 848, .w = 200, .h = 18 },
    .{ .x = 870, .y = 848, .w = 160, .h = 18 },
    .{ .x = 530, .y = 740, .w = 180, .h = 18 },
    .{ .x = 1450, .y = 740, .w = 200, .h = 18 },
    .{ .x = 2290, .y = 740, .w = 180, .h = 18 },
    .{ .x = 1410, .y = 632, .w = 180, .h = 18 },
    .{ .x = 330, .y = 632, .w = 140, .h = 18 },
    .{ .x = 2530, .y = 632, .w = 140, .h = 18 },
    .{ .x = 1300, .y = 612, .w = 40, .h = 344 },
    .{ .x = 1500, .y = 612, .w = 40, .h = 344 },
    .{ .x = 1190, .y = 948, .w = 100, .h = 18 },
    .{ .x = 1550, .y = 948, .w = 100, .h = 18 },
    .{ .x = 1185, .y = 612, .w = 110, .h = 18 },
    .{ .x = 1545, .y = 612, .w = 110, .h = 18 },
    .{ .x = 1330, .y = 604, .w = 180, .h = 18 },
    .{ .x = 1130, .y = 794, .w = 100, .h = 18 },
    .{ .x = 220, .y = 808, .w = 120, .h = 18 },
    .{ .x = 2660, .y = 808, .w = 120, .h = 18 },
};
pub const vessel_nexus_one_way = [_]u8{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1 };
pub const vessel_nexus_spawns = [_]Spawn{ .{ .x = 112, .y = 996 }, .{ .x = 412, .y = 996 }, .{ .x = 712, .y = 996 }, .{ .x = 1012, .y = 996 }, .{ .x = 1612, .y = 996 }, .{ .x = 1912, .y = 996 }, .{ .x = 2212, .y = 996 }, .{ .x = 2812, .y = 996 }, .{ .x = 1420, .y = 536 }, .{ .x = 400, .y = 564 }, .{ .x = 2600, .y = 564 }, .{ .x = 1180, .y = 726 }, .{ .x = 2544, .y = 888 } };
pub const vessel_nexus_slopes = [_]Slope{  };
pub const vessel_nexus_pads = [_]LaunchPad{  };

pub const skyseam_statics = [_]collision.AABB{
    .{ .x = 0, .y = 1064, .w = 3000, .h = 36 },
    .{ .x = 0, .y = 0, .w = 32, .h = 1100 },
    .{ .x = 2968, .y = 0, .w = 32, .h = 1100 },
    .{ .x = 50, .y = 0, .w = 700, .h = 32 },
    .{ .x = 2250, .y = 0, .w = 700, .h = 32 },
    .{ .x = 376, .y = 974, .w = 48, .h = 90 },
    .{ .x = 914, .y = 954, .w = 52, .h = 110 },
    .{ .x = 1472, .y = 974, .w = 56, .h = 90 },
    .{ .x = 2034, .y = 954, .w = 52, .h = 110 },
    .{ .x = 2576, .y = 974, .w = 48, .h = 90 },
    .{ .x = 660, .y = 1028, .w = 80, .h = 18 },
    .{ .x = 1175, .y = 1024, .w = 90, .h = 18 },
    .{ .x = 1735, .y = 1024, .w = 90, .h = 18 },
    .{ .x = 2260, .y = 1028, .w = 80, .h = 18 },
    .{ .x = 325, .y = 956, .w = 150, .h = 18 },
    .{ .x = 525, .y = 848, .w = 150, .h = 18 },
    .{ .x = 725, .y = 740, .w = 150, .h = 18 },
    .{ .x = 950, .y = 740, .w = 280, .h = 18 },
    .{ .x = 1290, .y = 632, .w = 150, .h = 18 },
    .{ .x = 1690, .y = 416, .w = 150, .h = 18 },
    .{ .x = 1915, .y = 416, .w = 280, .h = 18 },
    .{ .x = 2255, .y = 308, .w = 150, .h = 18 },
    .{ .x = 2480, .y = 308, .w = 240, .h = 18 },
    .{ .x = 2525, .y = 956, .w = 150, .h = 18 },
    .{ .x = 2325, .y = 848, .w = 150, .h = 18 },
    .{ .x = 2125, .y = 740, .w = 150, .h = 18 },
    .{ .x = 1770, .y = 740, .w = 280, .h = 18 },
    .{ .x = 1560, .y = 632, .w = 150, .h = 18 },
    .{ .x = 1160, .y = 416, .w = 150, .h = 18 },
    .{ .x = 805, .y = 416, .w = 280, .h = 18 },
    .{ .x = 595, .y = 308, .w = 150, .h = 18 },
    .{ .x = 280, .y = 308, .w = 240, .h = 18 },
    .{ .x = 1350, .y = 524, .w = 300, .h = 18 },
    .{ .x = 140, .y = 200, .w = 140, .h = 18 },
    .{ .x = 570, .y = 200, .w = 140, .h = 18 },
    .{ .x = 830, .y = 308, .w = 140, .h = 18 },
    .{ .x = 1040, .y = 200, .w = 140, .h = 18 },
    .{ .x = 1300, .y = 308, .w = 140, .h = 18 },
    .{ .x = 1510, .y = 200, .w = 160, .h = 18 },
    .{ .x = 1780, .y = 308, .w = 140, .h = 18 },
    .{ .x = 1990, .y = 200, .w = 140, .h = 18 },
    .{ .x = 2720, .y = 200, .w = 140, .h = 18 },
    .{ .x = 1390, .y = 956, .w = 220, .h = 18 },
    .{ .x = 1400, .y = 848, .w = 200, .h = 18 },
};
pub const skyseam_one_way = [_]u8{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 };
pub const skyseam_spawns = [_]Spawn{ .{ .x = 112, .y = 996 }, .{ .x = 712, .y = 996 }, .{ .x = 1012, .y = 996 }, .{ .x = 1312, .y = 996 }, .{ .x = 1612, .y = 996 }, .{ .x = 1912, .y = 996 }, .{ .x = 2212, .y = 996 }, .{ .x = 2512, .y = 996 }, .{ .x = 2812, .y = 996 }, .{ .x = 210, .y = 132 }, .{ .x = 640, .y = 132 }, .{ .x = 1110, .y = 132 }, .{ .x = 1590, .y = 132 }, .{ .x = 2060, .y = 132 }, .{ .x = 2790, .y = 132 }, .{ .x = 2330, .y = 240 } };
pub const skyseam_slopes = [_]Slope{ .{ .base_x = 109, .base_y = 1064, .run = 216, .grade_t = 0.5, .dir = 1 }, .{ .base_x = 2891, .base_y = 1064, .run = 216, .grade_t = 0.5, .dir = -1 }, .{ .base_x = 1230, .base_y = 740, .run = 216, .grade_t = 1, .dir = 1 } };
pub const skyseam_pads = [_]LaunchPad{  };

pub const NAMED_MAPS = [_]NamedMap{
    .{
        .id = "boxworks",
        .width = 960,
        .height = 540,
        .theme_id = 0,
        .statics = &boxworks_statics,
        .one_way = &boxworks_one_way,
        .spawns = &boxworks_spawns,
        .slopes = &boxworks_slopes,
        .launch_pads = &boxworks_pads,
    },
    .{
        .id = "boxworks-mini",
        .width = 1280,
        .height = 640,
        .theme_id = 1,
        .statics = &boxworks_mini_statics,
        .one_way = &boxworks_mini_one_way,
        .spawns = &boxworks_mini_spawns,
        .slopes = &boxworks_mini_slopes,
        .launch_pads = &boxworks_mini_pads,
    },
    .{
        .id = "boxworks-tower",
        .width = 1440,
        .height = 1080,
        .theme_id = 2,
        .statics = &boxworks_tower_statics,
        .one_way = &boxworks_tower_one_way,
        .spawns = &boxworks_tower_spawns,
        .slopes = &boxworks_tower_slopes,
        .launch_pads = &boxworks_tower_pads,
    },
    .{
        .id = "boxworks-practice",
        .width = 2600,
        .height = 900,
        .theme_id = 5,
        .statics = &boxworks_practice_statics,
        .one_way = &boxworks_practice_one_way,
        .spawns = &boxworks_practice_spawns,
        .slopes = &boxworks_practice_slopes,
        .launch_pads = &boxworks_practice_pads,
    },
    .{
        .id = "vessel-nexus",
        .width = 3000,
        .height = 1100,
        .theme_id = 0,
        .statics = &vessel_nexus_statics,
        .one_way = &vessel_nexus_one_way,
        .spawns = &vessel_nexus_spawns,
        .slopes = &vessel_nexus_slopes,
        .launch_pads = &vessel_nexus_pads,
    },
    .{
        .id = "skyseam",
        .width = 3000,
        .height = 1100,
        .theme_id = 1,
        .statics = &skyseam_statics,
        .one_way = &skyseam_one_way,
        .spawns = &skyseam_spawns,
        .slopes = &skyseam_slopes,
        .launch_pads = &skyseam_pads,
    },
};

/// Look a map up by its wire id. Returns null for an unknown id rather
/// than a default map — silently substituting geometry would desync a
/// replay instead of failing it.
pub fn findNamedMap(id: []const u8) ?*const NamedMap {
    for (&NAMED_MAPS) |*m| {
        if (std.mem.eql(u8, m.id, id)) return m;
    }
    return null;
}

const std = @import("std");
