const std = @import("std");
const root = @import("sim_root");

test "step increments the counter byte" {
    root.reset();
    const ptr = root.alloc_state();
    const size = root.state_size();
    root.step(ptr, size, ptr, 0, 16);
    root.step(ptr, size, ptr, 0, 16);
    root.step(ptr, size, ptr, 0, 16);
    try std.testing.expectEqual(@as(u32, 3), root.current_tick());

    const counter: *u32 = @ptrCast(@alignCast(ptr));
    try std.testing.expectEqual(@as(u32, 3), counter.*);
}

test "state_size is non-zero" {
    try std.testing.expect(root.state_size() > 0);
}

test "reset zeroes the counter" {
    const ptr = root.alloc_state();
    const size = root.state_size();
    root.step(ptr, size, ptr, 0, 16);
    root.reset();
    try std.testing.expectEqual(@as(u32, 0), root.current_tick());
}

test "rng nextU32 is deterministic given same seed" {
    var a: u32 = 1234567;
    var b: u32 = 1234567;
    for (0..100) |_| {
        a = root.rng.nextU32(a);
        b = root.rng.nextU32(b);
        try std.testing.expectEqual(a, b);
    }
}

test "rng nextU32 self-consistency over 1000 steps" {
    // Same seed must produce same final state regardless of how many
    // intermediate states we observe.
    var quiet: u32 = 42;
    for (0..1000) |_| quiet = root.rng.nextU32(quiet);

    var observed: u32 = 42;
    for (0..1000) |i| {
        observed = root.rng.nextU32(observed);
        if (i == 999) {
            try std.testing.expectEqual(quiet, observed);
        }
    }
}

test "rng nextU32 from seed 0 is non-zero" {
    // Catches the "RNG didn't actually run" class of bug.
    try std.testing.expect(root.rng.nextU32(0) != 0);
}

// ── map_gen (docs/map-design.md laws, ported from mapGen.test.ts) ────────

test "map_gen: same seed twice -> identical geometry" {
    const seeds = [_]u32{ 0, 1, 7, 1234, 999999 };
    for (seeds) |seed| {
        const a = root.map_gen.generateArena(seed);
        const b = root.map_gen.generateArena(seed);
        try std.testing.expectEqual(a.platform_count, b.platform_count);
        var i: usize = 0;
        while (i < a.platform_count) : (i += 1) {
            try std.testing.expectEqual(a.platforms[i].cx, b.platforms[i].cx);
            try std.testing.expectEqual(a.platforms[i].cy, b.platforms[i].cy);
            try std.testing.expectEqual(a.platforms[i].w, b.platforms[i].w);
            try std.testing.expectEqual(a.platforms[i].h, b.platforms[i].h);
            try std.testing.expectEqual(a.platforms[i].kind, b.platforms[i].kind);
        }
        try std.testing.expectEqual(a.spawn_count, b.spawn_count);
        var j: usize = 0;
        while (j < a.spawn_count) : (j += 1) {
            try std.testing.expectEqual(a.spawns[j].x, b.spawns[j].x);
            try std.testing.expectEqual(a.spawns[j].y, b.spawns[j].y);
        }
    }
}

test "map_gen: 60 seeds all pass the route-graph validator" {
    var seed: u32 = 0;
    while (seed < 60) : (seed += 1) {
        const cand = root.map_gen.generateArena(seed);
        const v = root.map_gen.validate(&cand);
        try std.testing.expect(v.ok);
    }
}

test "map_gen: 60 seeds have generous well-separated spawns" {
    var seed: u32 = 0;
    while (seed < 60) : (seed += 1) {
        const cand = root.map_gen.generateArena(seed);
        try std.testing.expect(cand.spawn_count >= 4);
        var i: usize = 0;
        while (i < cand.spawn_count) : (i += 1) {
            var j: usize = i + 1;
            while (j < cand.spawn_count) : (j += 1) {
                const a = cand.spawns[i];
                const b = cand.spawns[j];
                const dx = a.x - b.x;
                const dy = a.y - b.y;
                try std.testing.expect(@sqrt(dx * dx + dy * dy) >= root.map_gen.MIN_SPAWN_DIST);
            }
        }
    }
}

test "map_gen: 60 seeds stay within the platform headroom" {
    var seed: u32 = 0;
    while (seed < 60) : (seed += 1) {
        const cand = root.map_gen.generateArena(seed);
        try std.testing.expect(cand.platform_count <= root.map_gen.MAX_GEN_PLATFORMS);
        try std.testing.expect(cand.platform_count > 4); // frame alone is not the whole arena
    }
}

test "map_gen: world_state_generate_arena writes statics and meta" {
    var state: root.world_state.WorldState = std.mem.zeroes(root.world_state.WorldState);
    var meta: root.map_gen.GeneratedArenaMeta = std.mem.zeroes(root.map_gen.GeneratedArenaMeta);
    const written = root.map_gen.world_state_generate_arena(&state, 42, &meta);
    try std.testing.expect(written > 4);
    try std.testing.expectEqual(written, state.static_count);
    try std.testing.expect(meta.spawn_count >= 4);
    try std.testing.expect(meta.arena_w > 0);
    try std.testing.expect(meta.arena_h > 0);
}

// ── draft (2026-07-14) — native card-drafting offer generation ──────────
// Golden vectors generated by running the REAL TS draftWeights.ts +
// round.ts enterDrafting loop against the real crystalRoundsCards table
// (see sim/tools/gen_card_data.ts's comment + the throwaway generator
// script this was produced with — re-run if cards.ts or the weighting
// formula changes). This proves RNG-cursor AND selection parity against
// TS, not just "the Zig code runs" — every offer index and final cursor
// below is what TS itself produced for the same seed.

fn allTrueBools(comptime n: usize) [n]bool {
    var a: [n]bool = @splat(false);
    var i: usize = 0;
    while (i < n) : (i += 1) a[i] = true;
    return a;
}

test "draft.rollOffers: catch_up role, full 60-card pool, seed=12345 matches TS" {
    var pool_buf: [root.draft.gen.cards.len]u32 = undefined;
    for (0..root.draft.gen.cards.len) |i| pool_buf[i] = @intCast(i);
    const result = root.draft.rollOffers(12345, &pool_buf, .catch_up);
    try std.testing.expectEqual(@as(u32, 3), result.count);
    try std.testing.expectEqual(@as(u32, 59), result.offers[0]); // stolen-fangs
    try std.testing.expectEqual(@as(u32, 55), result.offers[1]); // bulwark-core
    try std.testing.expectEqual(@as(u32, 38), result.offers[2]); // heavy-coolant
    try std.testing.expectEqual(@as(u32, 2400459792), result.cursor);
}

test "draft.rollOffers: winner role (uniform weight), full pool, seed=12345 matches TS" {
    var pool_buf: [root.draft.gen.cards.len]u32 = undefined;
    for (0..root.draft.gen.cards.len) |i| pool_buf[i] = @intCast(i);
    const result = root.draft.rollOffers(12345, &pool_buf, .winner);
    try std.testing.expectEqual(@as(u32, 3), result.count);
    try std.testing.expectEqual(@as(u32, 58), result.offers[0]); // riot-mirror
    try std.testing.expectEqual(@as(u32, 54), result.offers[1]); // blink-dash
    try std.testing.expectEqual(@as(u32, 32), result.offers[2]); // frost-prism
    // Same cursor evolution as the catch_up case above: pickWeighted draws
    // exactly one nextFloat per call regardless of weights, so with the same
    // pool size and same number of loop iterations the cursor is identical
    // to the catch_up vector even though the picks differ — a structural
    // invariant confirmed against TS, not a coincidence.
    try std.testing.expectEqual(@as(u32, 2400459792), result.cursor);
}

test "draft.rollOffers: standard role, full pool, seed=777 matches TS" {
    var pool_buf: [root.draft.gen.cards.len]u32 = undefined;
    for (0..root.draft.gen.cards.len) |i| pool_buf[i] = @intCast(i);
    const result = root.draft.rollOffers(777, &pool_buf, .standard);
    try std.testing.expectEqual(@as(u32, 3), result.count);
    try std.testing.expectEqual(@as(u32, 41), result.offers[0]); // wide-parry
    try std.testing.expectEqual(@as(u32, 11), result.offers[1]); // seeker-facets
    try std.testing.expectEqual(@as(u32, 6), result.offers[2]); // i-rounds
    try std.testing.expectEqual(@as(u32, 486845128), result.cursor);
}

test "draft.rollOffers: catch_up role, tight 4-card pool, seed=999 matches TS" {
    var pool_buf: [4]u32 = .{ 0, 1, 2, 3 };
    const result = root.draft.rollOffers(999, &pool_buf, .catch_up);
    try std.testing.expectEqual(@as(u32, 3), result.count);
    try std.testing.expectEqual(@as(u32, 3), result.offers[0]); // triangle-rounds
    try std.testing.expectEqual(@as(u32, 1), result.offers[1]); // crystal-volley
    try std.testing.expectEqual(@as(u32, 2), result.offers[2]); // circle-rounds
    try std.testing.expectEqual(@as(u32, 3866534169), result.cursor);
}

test "draft.rollOffers: degenerate 1-card pool, seed=42 matches TS (target clamps to 1)" {
    var pool_buf: [1]u32 = .{0};
    const result = root.draft.rollOffers(42, &pool_buf, .catch_up);
    try std.testing.expectEqual(@as(u32, 1), result.count);
    try std.testing.expectEqual(@as(u32, 0), result.offers[0]); // raycast-prism
    try std.testing.expectEqual(@as(u32, 2581720956), result.cursor);
}

test "draft.rollOffers: empty pool returns zero offers and unchanged cursor" {
    const empty: []const u32 = &.{};
    const result = root.draft.rollOffers(1234, empty, .catch_up);
    try std.testing.expectEqual(@as(u32, 0), result.count);
    try std.testing.expectEqual(@as(u32, 1234), result.cursor);
}

test "draft.weightForCard: non-catch_up roles are always uniform weight 1" {
    for (root.draft.gen.cards) |entry| {
        try std.testing.expectEqual(@as(f64, 1), root.draft.weightForCard(entry, .standard));
        try std.testing.expectEqual(@as(f64, 1), root.draft.weightForCard(entry, .winner));
    }
}

test "draft.weightForCard: catch_up weight matches TS formula bounds (1..5)" {
    for (root.draft.gen.cards) |entry| {
        const w = root.draft.weightForCard(entry, .catch_up);
        try std.testing.expect(w >= 1 and w <= 5);
        var expected: f64 = 1;
        if (entry.catch_up_eligible) expected += 2;
        if (entry.rarity == 1) expected += 1;
        if (entry.rarity == 2 or entry.rarity == 3) expected += 2;
        try std.testing.expectEqual(expected, w);
    }
}

test "draft.poolIndices: unique cards already owned are excluded" {
    // Find any unique card in the real table to drive the test off real data
    // instead of a fabricated fixture.
    var unique_idx: ?usize = null;
    for (root.draft.gen.cards, 0..) |entry, i| {
        if (entry.unique) {
            unique_idx = i;
            break;
        }
    }
    try std.testing.expect(unique_idx != null);
    const owned = allTrueBools(root.draft.gen.cards.len);
    var not_owned: [root.draft.gen.cards.len]bool = @splat(false);
    const copies: [root.draft.gen.cards.len]u32 = @splat(0);
    var out_owned: [root.draft.gen.cards.len]u32 = undefined;
    var out_not_owned: [root.draft.gen.cards.len]u32 = undefined;
    const n_owned = root.draft.poolIndices(&owned, &copies, &out_owned);
    const n_not_owned = root.draft.poolIndices(&not_owned, &copies, &out_not_owned);
    // Every unique card should be present when nothing is "owned"...
    var found_in_not_owned = false;
    for (out_not_owned[0..n_not_owned]) |idx| {
        if (idx == unique_idx.?) found_in_not_owned = true;
    }
    try std.testing.expect(found_in_not_owned);
    // ...and absent when everything is "owned".
    var found_in_owned = false;
    for (out_owned[0..n_owned]) |idx| {
        if (idx == unique_idx.?) found_in_owned = true;
    }
    try std.testing.expect(!found_in_owned);
}

// ── draft phase-machine wiring (2026-07-14) — full step_world E2E ────────
// Unlike the golden-vector tests above (which call draft.rollOffers
// directly), these drive the REAL stepWorld orchestrator through a
// round-over -> drafting -> countdown cycle, proving the WIRING (phase
// transitions, WorldState field read/write, pick-commit export, entity
// reset timing) works end-to-end, not just the algorithm in isolation.

fn makeDraftTestState(player_count: u32) root.world_state.WorldState {
    var state: root.world_state.WorldState = std.mem.zeroes(root.world_state.WorldState);
    state.header.match_winner_idx = -1;
    state.header.round_winner_idx = -1;
    state.player_count = player_count;
    var i: u32 = 0;
    while (i < player_count) : (i += 1) {
        state.players[i].health = 100.0;
        state.players[i].flags.alive = true;
        state.players[i].draft_picked_offer = 0xFE;
        state.players[i].draft_offers = .{ 0xFFFF, 0xFFFF, 0xFFFF };
    }
    return state;
}

test "draft phase machine: round-over timer expiry rolls into drafting and offers both players" {
    var state = makeDraftTestState(2);
    state.header.round_phase = @intFromEnum(root.round.RoundPhase.round_over);
    state.header.countdown_remaining_ms = 1; // expires this tick
    state.header.round_winner_idx = 0; // p0 won -> p1 gets catch_up weighting
    state.header.rng_state = 12345;
    state.header.tick = 100;

    _ = root.world.stepWorld(&state, 16.667);

    try std.testing.expectEqual(@intFromEnum(root.round.RoundPhase.drafting), state.header.round_phase);
    try std.testing.expectEqual(@as(f64, root.round.DRAFT_WINDOW_MS), state.header.countdown_remaining_ms);
    try std.testing.expectEqual(@as(u32, 3), state.players[0].draft_offer_count);
    try std.testing.expectEqual(@as(u32, 3), state.players[1].draft_offer_count);
    try std.testing.expectEqual(@as(u8, 0xFF), state.players[0].draft_picked_offer);
    try std.testing.expectEqual(@as(u8, 0xFF), state.players[1].draft_picked_offer);
    // tick is incremented to 101 at the top of stepWorld before this runs.
    const expected_expiry: u32 = 101 + @as(u32, @intFromFloat(@ceil(root.round.DRAFT_WINDOW_MS / root.round.STEP_MS)));
    try std.testing.expectEqual(expected_expiry, state.header.drafting_expires_at_tick);
    // Different rng cursor per player role (winner vs catch_up) proven
    // upstream by the golden-vector tests above; here just confirm no
    // offer is the sentinel and offers are in-range card indices.
    for (state.players[0].draft_offers) |idx| try std.testing.expect(idx < root.draft.gen.cards.len);
    for (state.players[1].draft_offers) |idx| try std.testing.expect(idx < root.draft.gen.cards.len);
}

test "draft phase machine: match-already-won round-over parks instead of drafting" {
    var state = makeDraftTestState(2);
    state.header.round_phase = @intFromEnum(root.round.RoundPhase.round_over);
    state.header.countdown_remaining_ms = 1;
    state.header.match_winner_idx = 0; // match already decided
    state.header.rng_state = 999;

    _ = root.world.stepWorld(&state, 16.667);

    try std.testing.expectEqual(@intFromEnum(root.round.RoundPhase.round_over), state.header.round_phase);
    try std.testing.expectEqual(@as(f64, 0), state.header.countdown_remaining_ms);
    try std.testing.expectEqual(@as(u32, 0), state.players[0].draft_offer_count);
}

test "draft phase machine: pick-commit grants the card and unblocks all-picked exit" {
    var state = makeDraftTestState(2);
    state.header.round_phase = @intFromEnum(root.round.RoundPhase.round_over);
    state.header.countdown_remaining_ms = 1;
    state.header.rng_state = 555;
    state.header.tick = 0;
    _ = root.world.stepWorld(&state, 16.667); // -> drafting, offers rolled

    try std.testing.expectEqual(@intFromEnum(root.round.RoundPhase.drafting), state.header.round_phase);
    const p0_pick = state.players[0].draft_offers[0];
    const p1_pick = state.players[1].draft_offers[1];

    const rc0 = root.world.world_state_commit_draft_pick(&state, 0, 0);
    try std.testing.expectEqual(@as(u32, p0_pick), rc0);
    try std.testing.expectEqual(@as(u8, 1), state.players[0].card_count);
    try std.testing.expectEqual(p0_pick, state.players[0].card_ids[0]);
    try std.testing.expectEqual(@as(u8, 0), state.players[0].draft_picked_offer);

    // Double-commit is rejected (already picked).
    const rc0_again = root.world.world_state_commit_draft_pick(&state, 0, 1);
    try std.testing.expectEqual(@as(u32, 0xFFFFFFFF), rc0_again);
    try std.testing.expectEqual(@as(u8, 1), state.players[0].card_count); // unchanged

    const rc1 = root.world.world_state_commit_draft_pick(&state, 1, 1);
    try std.testing.expectEqual(@as(u32, p1_pick), rc1);
    try std.testing.expectEqual(p1_pick, state.players[1].card_ids[0]);

    // Both players picked -> the very next tick should exit to countdown,
    // even though drafting_expires_at_tick is still far in the future.
    _ = root.world.stepWorld(&state, 16.667);
    try std.testing.expectEqual(@intFromEnum(root.round.RoundPhase.countdown), state.header.round_phase);
    try std.testing.expectEqual(@as(u8, 0xFE), state.players[0].draft_picked_offer);
    try std.testing.expectEqual(@as(u8, 0xFE), state.players[1].draft_picked_offer);
    try std.testing.expectEqual(@as(u32, 1), state.header.round_index);
    // Cards persisted through the exit (not wiped by the new-round reset —
    // only health/alive/timed-buffs are reset, matching the pre-existing
    // "players keep score + buff durations" contract).
    try std.testing.expectEqual(@as(u8, 1), state.players[0].card_count);
    try std.testing.expectEqual(@as(u8, 1), state.players[1].card_count);
    try std.testing.expectEqual(@as(f64, 100.0), state.players[0].health);
}

test "draft phase machine: expiry auto-picks the first offer for unpicked drafters" {
    var state = makeDraftTestState(2);
    state.header.round_phase = @intFromEnum(root.round.RoundPhase.round_over);
    state.header.countdown_remaining_ms = 1;
    state.header.rng_state = 42;
    state.header.tick = 0;
    _ = root.world.stepWorld(&state, 16.667); // -> drafting

    const p0_first_offer = state.players[0].draft_offers[0];
    const p1_first_offer = state.players[1].draft_offers[0];
    // Nobody commits a pick. Fast-forward past drafting_expires_at_tick.
    state.header.tick = state.header.drafting_expires_at_tick;

    _ = root.world.stepWorld(&state, 16.667);

    try std.testing.expectEqual(@intFromEnum(root.round.RoundPhase.countdown), state.header.round_phase);
    try std.testing.expectEqual(@as(u8, 1), state.players[0].card_count);
    try std.testing.expectEqual(p0_first_offer, state.players[0].card_ids[0]);
    try std.testing.expectEqual(@as(u8, 1), state.players[1].card_count);
    try std.testing.expectEqual(p1_first_offer, state.players[1].card_ids[0]);
}

test "draft phase machine: unique card already owned is excluded from a fresh offer roll" {
    var state = makeDraftTestState(1);
    // Find a real unique card and pre-grant it to player 0.
    var unique_idx: ?u16 = null;
    for (root.draft.gen.cards, 0..) |entry, idx| {
        if (entry.unique) {
            unique_idx = @intCast(idx);
            break;
        }
    }
    try std.testing.expect(unique_idx != null);
    state.players[0].card_ids[0] = unique_idx.?;
    state.players[0].card_count = 1;
    state.header.round_phase = @intFromEnum(root.round.RoundPhase.round_over);
    state.header.countdown_remaining_ms = 1;
    state.header.rng_state = 8675309;

    _ = root.world.stepWorld(&state, 16.667);

    try std.testing.expectEqual(@intFromEnum(root.round.RoundPhase.drafting), state.header.round_phase);
    for (state.players[0].draft_offers[0..state.players[0].draft_offer_count]) |idx| {
        try std.testing.expect(idx != unique_idx.?);
    }
}

test "draft.poolIndices: maxStacks cap excludes cards already at cap" {
    var capped_idx: ?usize = null;
    var cap_value: u32 = 0;
    for (root.draft.gen.cards, 0..) |entry, i| {
        if (entry.max_stacks) |cap| {
            capped_idx = i;
            cap_value = cap;
            break;
        }
    }
    try std.testing.expect(capped_idx != null);
    const owned: [root.draft.gen.cards.len]bool = @splat(false);
    var copies: [root.draft.gen.cards.len]u32 = @splat(0);
    copies[capped_idx.?] = cap_value; // at cap
    var out: [root.draft.gen.cards.len]u32 = undefined;
    const n = root.draft.poolIndices(&owned, &copies, &out);
    var found = false;
    for (out[0..n]) |idx| {
        if (idx == capped_idx.?) found = true;
    }
    try std.testing.expect(!found);
}
